//! ADR-081 §4 cross-session serve ledger — brain-owned record of recall serves
//! and their scorer-assigned grades.
//!
//! Row creation (`record_serve`) implements the normative write side of the
//! ledger so the table is fully usable end to end, but wiring `memory.recall` to
//! call it is explicitly out of scope here (ADR-081 §5: the `served_by_profile_id`
//! serve-time stamp ships as a separate, latency-gated implementation PR, #394).
//! What this task wires up is the read side consumed by `brain.feedback` /
//! `brain.auto_feedback` when a caller supplies `serve_ledger_id` (ADR-081 §6):
//! dedup by `(scorer_run_id, id)`, the `accounting_profile_id` zero-weight
//! fail-safe, and grade backfill.
use khive_runtime::RuntimeError;
use khive_storage::types::{SqlStatement, SqlValue};
use khive_storage::SqlAccess;

fn sql_err(context: &str, e: impl std::fmt::Display) -> RuntimeError {
    RuntimeError::Internal(format!("serve ledger {context}: {e}"))
}

/// One row of `brain_serve_ledger` (ADR-081 §4 normative schema).
pub struct ServeLedgerRow {
    pub id: String,
    #[allow(dead_code)]
    pub namespace: String,
    #[allow(dead_code)]
    pub consumer_kind: String,
    pub served_by_profile_id: Option<String>,
    pub resolved_profile_id: Option<String>,
    #[allow(dead_code)]
    pub resolved_at: Option<i64>,
    /// `COALESCE(served_by_profile_id, resolved_profile_id)` — generated by SQLite,
    /// read back here rather than recomputed, so a future change to the generated
    /// expression cannot silently diverge from what the fold gate reads.
    pub accounting_profile_id: Option<String>,
    #[allow(dead_code)]
    pub target_id: String,
    #[allow(dead_code)]
    pub query_class: String,
    #[allow(dead_code)]
    pub query_raw: String,
    #[allow(dead_code)]
    pub served_at: i64,
    #[allow(dead_code)]
    pub grade: Option<String>,
    #[allow(dead_code)]
    pub graded_at: Option<i64>,
    /// The scorer run that last graded this row, if any — the dedup token.
    pub scorer_run_id: Option<String>,
}

fn row_text(row: &khive_storage::types::SqlRow, col: &str) -> Result<String, RuntimeError> {
    match row.get(col) {
        Some(SqlValue::Text(s)) => Ok(s.clone()),
        _ => Err(sql_err("read row", format!("missing {col} column"))),
    }
}

fn row_opt_text(row: &khive_storage::types::SqlRow, col: &str) -> Option<String> {
    match row.get(col) {
        Some(SqlValue::Text(s)) => Some(s.clone()),
        _ => None,
    }
}

fn row_opt_int(row: &khive_storage::types::SqlRow, col: &str) -> Option<i64> {
    match row.get(col) {
        Some(SqlValue::Integer(n)) => Some(*n),
        _ => None,
    }
}

fn row_int(row: &khive_storage::types::SqlRow, col: &str) -> Result<i64, RuntimeError> {
    match row.get(col) {
        Some(SqlValue::Integer(n)) => Ok(*n),
        _ => Err(sql_err("read row", format!("missing {col} column"))),
    }
}

/// Record a new serve row (the ADR-081 §4 write side). Not yet called by the
/// recall path (out of scope here); provided so the ledger's write contract is
/// implemented, not stubbed, ahead of that wiring.
#[allow(clippy::too_many_arguments)]
pub async fn record_serve(
    sql: &dyn SqlAccess,
    id: &str,
    namespace: &str,
    consumer_kind: &str,
    served_by_profile_id: Option<&str>,
    resolved_profile_id: Option<&str>,
    resolved_at: Option<i64>,
    target_id: &str,
    query_class: &str,
    query_raw: &str,
    served_at: i64,
) -> Result<(), RuntimeError> {
    let mut writer = sql.writer().await.map_err(|e| sql_err("writer", e))?;
    writer
        .execute(SqlStatement {
            sql: "INSERT INTO brain_serve_ledger \
                  (id, namespace, consumer_kind, served_by_profile_id, resolved_profile_id, \
                   resolved_at, target_id, query_class, query_raw, served_at) \
                  VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)"
                .into(),
            params: vec![
                SqlValue::Text(id.to_string()),
                SqlValue::Text(namespace.to_string()),
                SqlValue::Text(consumer_kind.to_string()),
                served_by_profile_id
                    .map(|s| SqlValue::Text(s.to_string()))
                    .unwrap_or(SqlValue::Null),
                resolved_profile_id
                    .map(|s| SqlValue::Text(s.to_string()))
                    .unwrap_or(SqlValue::Null),
                resolved_at.map(SqlValue::Integer).unwrap_or(SqlValue::Null),
                SqlValue::Text(target_id.to_string()),
                SqlValue::Text(query_class.to_string()),
                SqlValue::Text(query_raw.to_string()),
                SqlValue::Integer(served_at),
            ],
            label: Some("brain_serve_ledger_insert".into()),
        })
        .await
        .map_err(|e| sql_err("insert serve row", e))?;
    Ok(())
}

/// Fetch a serve ledger row by id.
pub async fn get_serve_row(
    sql: &dyn SqlAccess,
    id: &str,
) -> Result<Option<ServeLedgerRow>, RuntimeError> {
    let mut reader = sql.reader().await.map_err(|e| sql_err("reader", e))?;
    let row = reader
        .query_row(SqlStatement {
            sql: "SELECT id, namespace, consumer_kind, served_by_profile_id, \
                  resolved_profile_id, resolved_at, accounting_profile_id, target_id, \
                  query_class, query_raw, served_at, grade, graded_at, scorer_run_id \
                  FROM brain_serve_ledger WHERE id = ?1"
                .into(),
            params: vec![SqlValue::Text(id.to_string())],
            label: Some("brain_serve_ledger_get".into()),
        })
        .await
        .map_err(|e| sql_err("read row", e))?;

    let Some(row) = row else {
        return Ok(None);
    };

    Ok(Some(ServeLedgerRow {
        id: row_text(&row, "id")?,
        namespace: row_text(&row, "namespace")?,
        consumer_kind: row_text(&row, "consumer_kind")?,
        served_by_profile_id: row_opt_text(&row, "served_by_profile_id"),
        resolved_profile_id: row_opt_text(&row, "resolved_profile_id"),
        resolved_at: row_opt_int(&row, "resolved_at"),
        accounting_profile_id: row_opt_text(&row, "accounting_profile_id"),
        target_id: row_text(&row, "target_id")?,
        query_class: row_text(&row, "query_class")?,
        query_raw: row_text(&row, "query_raw")?,
        served_at: row_int(&row, "served_at")?,
        grade: row_opt_text(&row, "grade"),
        graded_at: row_opt_int(&row, "graded_at"),
        scorer_run_id: row_opt_text(&row, "scorer_run_id"),
    }))
}

/// Backfill a serve row's grade after a scorer emits feedback for it
/// (ADR-081 §6: "the fold... backfills the ledger row's grade").
///
/// Also stamps `scorer_run_id`, which is what `dedup` reads on a later call —
/// idempotent per-row by `(scorer_run_id, id)` (ADR-081 §4).
pub async fn backfill_grade(
    sql: &dyn SqlAccess,
    id: &str,
    grade: &str,
    graded_at_us: i64,
    scorer_run_id: &str,
) -> Result<(), RuntimeError> {
    let mut writer = sql.writer().await.map_err(|e| sql_err("writer", e))?;
    writer
        .execute(SqlStatement {
            sql: "UPDATE brain_serve_ledger SET grade = ?1, graded_at = ?2, scorer_run_id = ?3 \
                  WHERE id = ?4"
                .into(),
            params: vec![
                SqlValue::Text(grade.to_string()),
                SqlValue::Integer(graded_at_us),
                SqlValue::Text(scorer_run_id.to_string()),
                SqlValue::Text(id.to_string()),
            ],
            label: Some("brain_serve_ledger_backfill_grade".into()),
        })
        .await
        .map_err(|e| sql_err("backfill grade", e))?;
    Ok(())
}

/// Outcome of resolving a `(scorer_run_id, serve_ledger_id)` pair against the
/// ledger, before the fold gate runs.
pub enum ServeLedgerResolution {
    /// This exact `(scorer_run_id, serve_ledger_id)` pair was already graded —
    /// the caller must treat this emission as a no-op (ADR-081 §2 dedup).
    AlreadyGraded,
    /// Row found and not yet graded by this `scorer_run_id`. Carries the
    /// accounting profile id to fold under, or `None` if unresolved (the
    /// caller must force a zero-weight fold — ADR-081 §4 fail-safe).
    Proceed {
        accounting_profile_id: Option<String>,
    },
    /// No row exists for `serve_ledger_id`.
    NotFound,
}

/// Resolve a `(scorer_run_id, serve_ledger_id)` pair against the ledger.
pub async fn resolve(
    sql: &dyn SqlAccess,
    serve_ledger_id: &str,
    scorer_run_id: &str,
) -> Result<ServeLedgerResolution, RuntimeError> {
    let Some(row) = get_serve_row(sql, serve_ledger_id).await? else {
        return Ok(ServeLedgerResolution::NotFound);
    };
    if row.scorer_run_id.as_deref() == Some(scorer_run_id) {
        return Ok(ServeLedgerResolution::AlreadyGraded);
    }
    Ok(ServeLedgerResolution::Proceed {
        accounting_profile_id: row.accounting_profile_id,
    })
}
