//! ADR-081 §4 cross-session serve ledger — brain-owned record of recall serves
//! and their scorer-assigned grades.
//!
//! Row creation (`record_serve`) implements the normative write side of the
//! ledger; `memory.recall` wires into it via `brain.record_serve` (ADR-081 §5,
//! #394) to stamp `served_by_profile_id` and append the ledger row off the
//! response path. The read side is consumed by `brain.feedback` /
//! `brain.auto_feedback` when a caller supplies `serve_ledger_id` (ADR-081 §6):
//! dedup by `(scorer_run_id, id)`, the `accounting_profile_id` zero-weight
//! fail-safe, and grade backfill.
use khive_runtime::RuntimeError;
use khive_storage::types::{SqlStatement, SqlValue};
use khive_storage::SqlAccess;

pub use khive_brain_core::compute_query_class;
use khive_brain_core::ServeAttribution;

fn sql_err(context: &str, e: impl std::fmt::Display) -> RuntimeError {
    RuntimeError::Internal(format!("serve ledger {context}: {e}"))
}

/// One row of `brain_serve_ledger` (ADR-081 §4 normative schema).
pub struct ServeLedgerRow {
    pub id: String,
    #[allow(dead_code)]
    pub namespace: String,
    #[allow(dead_code)]
    pub consumer_kind: String,
    pub served_by_profile_id: Option<String>,
    pub resolved_profile_id: Option<String>,
    #[allow(dead_code)]
    pub resolved_at: Option<i64>,
    /// `COALESCE(served_by_profile_id, resolved_profile_id)` — generated by SQLite,
    /// read back here rather than recomputed, so a future change to the generated
    /// expression cannot silently diverge from what the fold gate reads.
    pub accounting_profile_id: Option<String>,
    /// The tri-state marker stamped at serve time (ADR-081 amendment), or
    /// `None` for a legacy row written before the column existed, or one
    /// where the marker was unrecognized.
    pub serve_attribution: Option<ServeAttribution>,
    #[allow(dead_code)]
    pub target_id: String,
    #[allow(dead_code)]
    pub query_class: String,
    #[allow(dead_code)]
    pub query_raw: String,
    #[allow(dead_code)]
    pub served_at: i64,
    #[allow(dead_code)]
    pub grade: Option<String>,
    #[allow(dead_code)]
    pub graded_at: Option<i64>,
    /// The scorer run that last graded this row, if any — the dedup token.
    pub scorer_run_id: Option<String>,
}

fn row_text(row: &khive_storage::types::SqlRow, col: &str) -> Result<String, RuntimeError> {
    match row.get(col) {
        Some(SqlValue::Text(s)) => Ok(s.clone()),
        _ => Err(sql_err("read row", format!("missing {col} column"))),
    }
}

fn row_opt_text(row: &khive_storage::types::SqlRow, col: &str) -> Option<String> {
    match row.get(col) {
        Some(SqlValue::Text(s)) => Some(s.clone()),
        _ => None,
    }
}

fn row_opt_int(row: &khive_storage::types::SqlRow, col: &str) -> Option<i64> {
    match row.get(col) {
        Some(SqlValue::Integer(n)) => Some(*n),
        _ => None,
    }
}

fn row_int(row: &khive_storage::types::SqlRow, col: &str) -> Result<i64, RuntimeError> {
    match row.get(col) {
        Some(SqlValue::Integer(n)) => Ok(*n),
        _ => Err(sql_err("read row", format!("missing {col} column"))),
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ServeLedgerInsert {
    pub id: String,
    pub target_id: String,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(crate) struct ServeLedgerBatchSummary {
    pub written: usize,
    pub skipped: usize,
}

#[allow(clippy::too_many_arguments)]
fn serve_ledger_insert_statement(
    row: &ServeLedgerInsert,
    namespace: &str,
    consumer_kind: &str,
    served_by_profile_id: Option<&str>,
    resolved_profile_id: Option<&str>,
    resolved_at: Option<i64>,
    query_class: &str,
    query_raw: &str,
    served_at: i64,
    serve_attribution: Option<&str>,
) -> SqlStatement {
    SqlStatement {
        sql: "INSERT INTO brain_serve_ledger \
              (id, namespace, consumer_kind, served_by_profile_id, resolved_profile_id, \
               resolved_at, target_id, query_class, query_raw, served_at, serve_attribution) \
              VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) \
              ON CONFLICT(namespace, target_id, query_class, served_at) DO NOTHING"
            .into(),
        params: vec![
            SqlValue::Text(row.id.clone()),
            SqlValue::Text(namespace.to_string()),
            SqlValue::Text(consumer_kind.to_string()),
            served_by_profile_id
                .map(|s| SqlValue::Text(s.to_string()))
                .unwrap_or(SqlValue::Null),
            resolved_profile_id
                .map(|s| SqlValue::Text(s.to_string()))
                .unwrap_or(SqlValue::Null),
            resolved_at.map(SqlValue::Integer).unwrap_or(SqlValue::Null),
            SqlValue::Text(row.target_id.clone()),
            SqlValue::Text(query_class.to_string()),
            SqlValue::Text(query_raw.to_string()),
            SqlValue::Integer(served_at),
            serve_attribution
                .map(|s| SqlValue::Text(s.to_string()))
                .unwrap_or(SqlValue::Null),
        ],
        label: Some("brain_serve_ledger_insert".into()),
    }
}

#[allow(clippy::too_many_arguments)]
pub(crate) async fn record_serves(
    sql: &dyn SqlAccess,
    rows: &[ServeLedgerInsert],
    namespace: &str,
    consumer_kind: &str,
    served_by_profile_id: Option<&str>,
    resolved_profile_id: Option<&str>,
    resolved_at: Option<i64>,
    query_class: &str,
    query_raw: &str,
    served_at: i64,
    serve_attribution: Option<&str>,
) -> Result<ServeLedgerBatchSummary, RuntimeError> {
    if rows.is_empty() {
        return Ok(ServeLedgerBatchSummary::default());
    }

    let statements = rows
        .iter()
        .map(|row| {
            serve_ledger_insert_statement(
                row,
                namespace,
                consumer_kind,
                served_by_profile_id,
                resolved_profile_id,
                resolved_at,
                query_class,
                query_raw,
                served_at,
                serve_attribution,
            )
        })
        .collect();
    let mut writer = sql.writer().await.map_err(|e| sql_err("writer", e))?;
    let affected = writer
        .execute_batch(statements)
        .await
        .map_err(|e| sql_err("insert serve batch", e))?;
    let written = usize::try_from(affected)
        .map_err(|_| sql_err("insert serve batch", "affected row count exceeds usize"))?;
    let skipped = rows.len().checked_sub(written).ok_or_else(|| {
        sql_err(
            "insert serve batch",
            format!(
                "affected row count {written} exceeds input count {}",
                rows.len()
            ),
        )
    })?;

    Ok(ServeLedgerBatchSummary { written, skipped })
}

/// Record a new serve row (the ADR-081 §4 write side). Returns `Ok(true)` when
/// the row was written, `Ok(false)` when an exact-key duplicate was tolerated
/// (the natural key `(namespace, target_id, query_class, served_at)` already
/// has a row — a duplicate drain of the same batch, not an error).
#[allow(clippy::too_many_arguments)]
pub async fn record_serve(
    sql: &dyn SqlAccess,
    id: &str,
    namespace: &str,
    consumer_kind: &str,
    served_by_profile_id: Option<&str>,
    resolved_profile_id: Option<&str>,
    resolved_at: Option<i64>,
    target_id: &str,
    query_class: &str,
    query_raw: &str,
    served_at: i64,
    serve_attribution: Option<&str>,
) -> Result<bool, RuntimeError> {
    let rows = [ServeLedgerInsert {
        id: id.to_string(),
        target_id: target_id.to_string(),
    }];
    let summary = record_serves(
        sql,
        &rows,
        namespace,
        consumer_kind,
        served_by_profile_id,
        resolved_profile_id,
        resolved_at,
        query_class,
        query_raw,
        served_at,
        serve_attribution,
    )
    .await?;
    Ok(summary.written == 1)
}

/// Fetch a serve ledger row by id.
pub async fn get_serve_row(
    sql: &dyn SqlAccess,
    id: &str,
) -> Result<Option<ServeLedgerRow>, RuntimeError> {
    let mut reader = sql.reader().await.map_err(|e| sql_err("reader", e))?;
    let row = reader
        .query_row(SqlStatement {
            sql: "SELECT id, namespace, consumer_kind, served_by_profile_id, \
                  resolved_profile_id, resolved_at, accounting_profile_id, target_id, \
                  query_class, query_raw, served_at, grade, graded_at, scorer_run_id, \
                  serve_attribution \
                  FROM brain_serve_ledger WHERE id = ?1"
                .into(),
            params: vec![SqlValue::Text(id.to_string())],
            label: Some("brain_serve_ledger_get".into()),
        })
        .await
        .map_err(|e| sql_err("read row", e))?;

    let Some(row) = row else {
        return Ok(None);
    };

    Ok(Some(ServeLedgerRow {
        id: row_text(&row, "id")?,
        namespace: row_text(&row, "namespace")?,
        consumer_kind: row_text(&row, "consumer_kind")?,
        served_by_profile_id: row_opt_text(&row, "served_by_profile_id"),
        resolved_profile_id: row_opt_text(&row, "resolved_profile_id"),
        resolved_at: row_opt_int(&row, "resolved_at"),
        accounting_profile_id: row_opt_text(&row, "accounting_profile_id"),
        serve_attribution: ServeAttribution::from_column(
            row_opt_text(&row, "serve_attribution").as_deref(),
        ),
        target_id: row_text(&row, "target_id")?,
        query_class: row_text(&row, "query_class")?,
        query_raw: row_text(&row, "query_raw")?,
        served_at: row_int(&row, "served_at")?,
        grade: row_opt_text(&row, "grade"),
        graded_at: row_opt_int(&row, "graded_at"),
        scorer_run_id: row_opt_text(&row, "scorer_run_id"),
    }))
}

/// Backfill a serve row's grade after a scorer emits feedback for it
/// (ADR-081 §6: "the fold... backfills the ledger row's grade").
///
/// Also stamps `scorer_run_id`, which is what `dedup` reads on a later call —
/// idempotent per-row by `(scorer_run_id, id)` (ADR-081 §4).
pub async fn backfill_grade(
    sql: &dyn SqlAccess,
    id: &str,
    grade: &str,
    graded_at_us: i64,
    scorer_run_id: &str,
) -> Result<(), RuntimeError> {
    let mut writer = sql.writer().await.map_err(|e| sql_err("writer", e))?;
    writer
        .execute(SqlStatement {
            sql: "UPDATE brain_serve_ledger SET grade = ?1, graded_at = ?2, scorer_run_id = ?3 \
                  WHERE id = ?4"
                .into(),
            params: vec![
                SqlValue::Text(grade.to_string()),
                SqlValue::Integer(graded_at_us),
                SqlValue::Text(scorer_run_id.to_string()),
                SqlValue::Text(id.to_string()),
            ],
            label: Some("brain_serve_ledger_backfill_grade".into()),
        })
        .await
        .map_err(|e| sql_err("backfill grade", e))?;
    Ok(())
}

/// Outcome of resolving a `(scorer_run_id, serve_ledger_id)` pair against the
/// ledger, before the fold gate runs.
pub enum ServeLedgerResolution {
    /// This exact `(scorer_run_id, serve_ledger_id)` pair was already graded —
    /// the caller must treat this emission as a no-op (ADR-081 §2 dedup).
    AlreadyGraded,
    /// Row found and not yet graded by this `scorer_run_id`. Carries the
    /// accounting profile id to fold under, or `None` if unresolved (the
    /// caller must force a zero-weight fold — ADR-081 §4 fail-safe) — unless
    /// `serve_attribution` is the stored `unspecified` marker, which keeps the
    /// legacy binding/default fallback permitted instead of forcing zero.
    Proceed {
        accounting_profile_id: Option<String>,
        serve_attribution: Option<ServeAttribution>,
    },
    /// No row exists for `serve_ledger_id`.
    NotFound,
}

/// Resolve a `(scorer_run_id, serve_ledger_id)` pair against the ledger.
pub async fn resolve(
    sql: &dyn SqlAccess,
    serve_ledger_id: &str,
    scorer_run_id: &str,
) -> Result<ServeLedgerResolution, RuntimeError> {
    let Some(row) = get_serve_row(sql, serve_ledger_id).await? else {
        return Ok(ServeLedgerResolution::NotFound);
    };
    if row.scorer_run_id.as_deref() == Some(scorer_run_id) {
        return Ok(ServeLedgerResolution::AlreadyGraded);
    }
    Ok(ServeLedgerResolution::Proceed {
        accounting_profile_id: row.accounting_profile_id,
        serve_attribution: row.serve_attribution,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::{Arc, Mutex};

    struct CapturingSqlAccess {
        writer_acquisitions: Arc<AtomicUsize>,
        execute_batch_calls: Arc<AtomicUsize>,
        batches: Arc<Mutex<Vec<Vec<SqlStatement>>>>,
        affected: u64,
    }

    impl CapturingSqlAccess {
        fn new(affected: u64) -> Self {
            Self {
                writer_acquisitions: Arc::new(AtomicUsize::new(0)),
                execute_batch_calls: Arc::new(AtomicUsize::new(0)),
                batches: Arc::new(Mutex::new(Vec::new())),
                affected,
            }
        }
    }

    struct CapturingWriter {
        execute_batch_calls: Arc<AtomicUsize>,
        batches: Arc<Mutex<Vec<Vec<SqlStatement>>>>,
        affected: u64,
    }

    #[async_trait::async_trait]
    impl khive_storage::SqlReader for CapturingWriter {
        async fn query_row(
            &mut self,
            _statement: SqlStatement,
        ) -> khive_storage::StorageResult<Option<khive_storage::SqlRow>> {
            panic!("record_serves must not issue reads")
        }

        async fn query_all(
            &mut self,
            _statement: SqlStatement,
        ) -> khive_storage::StorageResult<Vec<khive_storage::SqlRow>> {
            panic!("record_serves must not issue reads")
        }

        async fn query_scalar(
            &mut self,
            _statement: SqlStatement,
        ) -> khive_storage::StorageResult<Option<SqlValue>> {
            panic!("record_serves must not issue reads")
        }

        async fn explain(
            &mut self,
            _statement: SqlStatement,
        ) -> khive_storage::StorageResult<Vec<khive_storage::SqlRow>> {
            panic!("record_serves must not issue reads")
        }
    }

    #[async_trait::async_trait]
    impl khive_storage::SqlWriter for CapturingWriter {
        async fn execute(&mut self, _statement: SqlStatement) -> khive_storage::StorageResult<u64> {
            panic!("record_serves must use one execute_batch call")
        }

        async fn execute_batch(
            &mut self,
            statements: Vec<SqlStatement>,
        ) -> khive_storage::StorageResult<u64> {
            self.execute_batch_calls.fetch_add(1, Ordering::SeqCst);
            self.batches.lock().unwrap().push(statements);
            Ok(self.affected)
        }

        async fn execute_script(&mut self, _script: String) -> khive_storage::StorageResult<()> {
            panic!("record_serves must not execute raw scripts")
        }
    }

    #[async_trait::async_trait]
    impl SqlAccess for CapturingSqlAccess {
        async fn reader(&self) -> khive_storage::StorageResult<Box<dyn khive_storage::SqlReader>> {
            panic!("record_serves must not acquire a reader")
        }

        async fn writer(&self) -> khive_storage::StorageResult<Box<dyn khive_storage::SqlWriter>> {
            self.writer_acquisitions.fetch_add(1, Ordering::SeqCst);
            Ok(Box::new(CapturingWriter {
                execute_batch_calls: Arc::clone(&self.execute_batch_calls),
                batches: Arc::clone(&self.batches),
                affected: self.affected,
            }))
        }

        async fn atomic_unit(
            &self,
            _op: khive_storage::AtomicUnitOp,
        ) -> khive_storage::StorageResult<Box<dyn std::any::Any + Send>> {
            panic!("record_serves must use the SqlWriter batch seam")
        }
    }

    fn text_param(statement: &SqlStatement, index: usize) -> &str {
        match &statement.params[index] {
            SqlValue::Text(value) => value,
            other => panic!("parameter {index} must be text, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn record_serves_empty_input_does_not_acquire_writer() {
        let sql = CapturingSqlAccess::new(0);
        let summary = record_serves(
            &sql,
            &[],
            "local",
            "recall",
            Some("profile-a"),
            None,
            None,
            "class-a",
            "raw query",
            7,
            None,
        )
        .await
        .expect("empty batch must succeed");

        assert_eq!(summary, ServeLedgerBatchSummary::default());
        assert_eq!(sql.writer_acquisitions.load(Ordering::SeqCst), 0);
        assert_eq!(sql.execute_batch_calls.load(Ordering::SeqCst), 0);
        assert!(sql.batches.lock().unwrap().is_empty());
    }

    #[tokio::test]
    async fn record_serves_uses_one_ordered_batch_and_affected_count() {
        let sql = CapturingSqlAccess::new(2);
        let rows = [
            ServeLedgerInsert {
                id: "row-a".into(),
                target_id: "target-a".into(),
            },
            ServeLedgerInsert {
                id: "row-b".into(),
                target_id: "target-b".into(),
            },
            ServeLedgerInsert {
                id: "row-c".into(),
                target_id: "target-c".into(),
            },
        ];

        let summary = record_serves(
            &sql,
            &rows,
            "namespace-a",
            "recall",
            Some("served-profile"),
            Some("resolved-profile"),
            Some(123),
            "class-a",
            "Literal Raw Query",
            456,
            Some("profile"),
        )
        .await
        .expect("captured batch must succeed");

        assert_eq!(
            summary,
            ServeLedgerBatchSummary {
                written: 2,
                skipped: 1,
            }
        );
        assert_eq!(sql.writer_acquisitions.load(Ordering::SeqCst), 1);
        assert_eq!(sql.execute_batch_calls.load(Ordering::SeqCst), 1);

        let batches = sql.batches.lock().unwrap();
        assert_eq!(batches.len(), 1);
        let statements = &batches[0];
        assert_eq!(statements.len(), rows.len());
        for (statement, row) in statements.iter().zip(rows.iter()) {
            assert!(statement
                .sql
                .ends_with("ON CONFLICT(namespace, target_id, query_class, served_at) DO NOTHING"));
            assert_eq!(
                statement.label.as_deref(),
                Some("brain_serve_ledger_insert")
            );
            assert_eq!(text_param(statement, 0), row.id.as_str());
            assert_eq!(text_param(statement, 1), "namespace-a");
            assert_eq!(text_param(statement, 2), "recall");
            assert_eq!(text_param(statement, 3), "served-profile");
            assert_eq!(text_param(statement, 4), "resolved-profile");
            assert!(matches!(
                statement.params.get(5),
                Some(SqlValue::Integer(123))
            ));
            assert_eq!(text_param(statement, 6), row.target_id.as_str());
            assert_eq!(text_param(statement, 7), "class-a");
            assert_eq!(text_param(statement, 8), "Literal Raw Query");
            assert!(matches!(
                statement.params.get(9),
                Some(SqlValue::Integer(456))
            ));
            assert_eq!(text_param(statement, 10), "profile");
        }
    }

    #[tokio::test]
    async fn record_serves_rolls_back_earlier_rows_on_late_id_collision() {
        let dir = tempfile::tempdir().expect("tempdir");
        let db_path = dir.path().join("serve-ledger-batch-rollback.db");
        let pool = Arc::new(
            khive_db::ConnectionPool::new(khive_db::PoolConfig {
                path: Some(db_path),
                write_queue_enabled: false,
                ..khive_db::PoolConfig::default()
            })
            .expect("pool"),
        );
        {
            let mut writer = pool.writer().expect("writer");
            khive_db::run_migrations(writer.conn_mut()).expect("migrations");
        }
        let sql: Arc<dyn SqlAccess> = Arc::new(khive_db::SqlBridge::new(Arc::clone(&pool), true));

        record_serve(
            sql.as_ref(),
            "colliding-id",
            "local",
            "recall",
            None,
            None,
            None,
            "preexisting-target",
            "preexisting-class",
            "preexisting query",
            1,
            None,
        )
        .await
        .expect("precondition row must be inserted");

        let rows = [
            ServeLedgerInsert {
                id: "must-roll-back".into(),
                target_id: "fresh-target".into(),
            },
            ServeLedgerInsert {
                id: "colliding-id".into(),
                target_id: "different-target".into(),
            },
        ];
        record_serves(
            sql.as_ref(),
            &rows,
            "local",
            "recall",
            None,
            None,
            None,
            "batch-class",
            "batch query",
            2,
            None,
        )
        .await
        .expect_err("late primary-key collision must fail the whole batch");

        assert!(
            get_serve_row(sql.as_ref(), "must-roll-back")
                .await
                .expect("rollback probe")
                .is_none(),
            "the earlier statement must roll back when a later ID collides"
        );
        assert!(
            get_serve_row(sql.as_ref(), "colliding-id")
                .await
                .expect("precondition probe")
                .is_some(),
            "the pre-existing colliding row must remain"
        );
    }

    /// Fork C slice 2: proves `record_serve`'s single-row compatibility batch
    /// is actually enqueued on the pool's shared `WriterTaskHandle` channel
    /// when the write queue is enabled.
    ///
    /// Deliberately NOT a wall-clock/occupier-timing test — see the sibling
    /// `fold_gate::tests::fold_gate_apply_routes_through_writer_task_when_flag_enabled`
    /// doc comment for why real SQLite file-level locking makes elapsed time
    /// alone vacuous here. Instead this reads `WriterTaskHandle::queue_depth`
    /// directly while an occupier deterministically holds the writer task's
    /// one drain slot open (parked on a oneshot via `blocking_recv`, not a
    /// sleep/timing race).
    ///
    /// Deliberately NOT built via a full `KhiveRuntime` + the
    /// `KHIVE_WRITE_QUEUE` env var: that env var is process-global and this
    /// crate's other tests are not `#[serial]` against it, so a window where
    /// it is set here could leak into a concurrently-scheduled test's own
    /// `KhiveRuntime::new` and unexpectedly flip its pool's write-queue flag
    /// (see `fold_gate::tests::fold_gate_apply_routes_through_writer_task_when_flag_enabled`'s
    /// doc comment for the concrete failure this caused before both tests
    /// were rewritten to avoid the env var). Constructing the pool directly
    /// with `write_queue_enabled: true` in the config literal, and driving
    /// `record_serve` over a bare `SqlBridge` instead of a full
    /// `KhiveRuntime`, sidesteps global mutable state entirely.
    #[tokio::test]
    async fn record_serve_routes_through_writer_task_when_flag_enabled() {
        let dir = tempfile::tempdir().expect("tempdir");
        let db_path = dir.path().join("serve-ledger-write-queue-routing.db");
        let pool_cfg = khive_db::PoolConfig {
            path: Some(db_path),
            write_queue_enabled: true,
            ..khive_db::PoolConfig::default()
        };
        let pool = std::sync::Arc::new(khive_db::ConnectionPool::new(pool_cfg).expect("pool"));
        {
            let mut writer = pool.writer().expect("writer");
            khive_db::run_migrations(writer.conn_mut()).expect("migrations");
        }
        let sql: std::sync::Arc<dyn SqlAccess> =
            std::sync::Arc::new(khive_db::SqlBridge::new(std::sync::Arc::clone(&pool), true));

        let writer_task = pool
            .writer_task_handle()
            .unwrap()
            .expect("writer task must be spawned with the flag on for a file-backed pool");

        let (started_tx, started_rx) = tokio::sync::oneshot::channel::<()>();
        let (release_tx, release_rx) = tokio::sync::oneshot::channel::<()>();
        let occupier = {
            let writer_task = writer_task.clone();
            tokio::spawn(async move {
                writer_task
                    .send(move |_conn| {
                        let _ = started_tx.send(());
                        let _ = release_rx.blocking_recv();
                        Ok::<(), khive_storage::StorageError>(())
                    })
                    .await
            })
        };

        started_rx
            .await
            .expect("occupier must signal it has started running inside the writer task");
        assert_eq!(
            writer_task.queue_depth(),
            0,
            "channel must start empty once the occupier has been dequeued and is running"
        );

        let record_task = tokio::spawn(async move {
            record_serve(
                sql.as_ref(),
                "write-queue-routing-row",
                "local",
                "recall",
                Some("profile-a"),
                None,
                None,
                "write-queue-routing-target",
                "write-queue-routing-class",
                "write queue routing test query",
                1_700_000_000_000_000,
                Some("profile"),
            )
            .await
        });

        let mut saw_enqueued = false;
        for _ in 0..100 {
            if writer_task.queue_depth() >= 1 {
                saw_enqueued = true;
                break;
            }
            tokio::time::sleep(std::time::Duration::from_millis(5)).await;
        }
        assert!(
            saw_enqueued,
            "record_serve's write request never appeared in the writer task's \
             channel while the occupier held the single drain slot — \
             SqliteWriter::execute_batch is not routing this single-row write \
             through the shared writer task"
        );

        release_tx
            .send(())
            .expect("occupier must still be waiting on the release signal");
        occupier
            .await
            .expect("occupier task must not panic")
            .expect("occupier write must succeed");

        let inserted = record_task
            .await
            .expect("record_task must not panic")
            .expect("record_serve must succeed once unblocked");
        assert!(inserted, "record_serve must report a fresh row insert");
    }
}
