//! Write-time secret detection gate.
//!
//! Scans caller-supplied content strings before any storage write. A match
//! causes a hard `RuntimeError::SecretDetected` that names the detector and
//! carries a masked excerpt internally. Its display names the rule and trigger
//! without echoing any candidate text.
//!
//! Scope: **credentials only** — API keys, tokens, private keys, passwords,
//! and connection strings with embedded credentials. General PII (emails,
//! phone numbers, company names) is intentionally NOT blocked.
//!
//! Detection is layered, cheap-first:
//! 1. **Known-prefix / known-shape patterns** — AWS AKIA/ASIA, GitHub tokens,
//!    OpenAI `sk-proj-`, Anthropic `sk-ant-`, Stripe live keys, Fly.io tokens,
//!    Vercel secrets, Slack `xox*`, JWT triples, PEM private-key headers, Age
//!    secret keys, URL userinfo (`scheme://user:pass@`).
//! 2. **High-entropy token heuristic** — base64/hex/base64url runs ≥ 24 chars
//!    near a trigger word (key, secret, password, credential, bearer, auth,
//!    apikey, api_key, access_key, private_key). A standalone `token` still
//!    triggers opaque entropy detection, but does not by itself label a UUID
//!    as a credential; compound identifiers such as `tokenizer_*` and
//!    `token_count` remain excluded.
//!
//! Credential-shaped labels and assignments dominate the allowlist below.
//! Public VCS revisions and plausible file paths remain exempt in ordinary
//! technical prose, while path segments are still scanned independently.
//!
//! Full exemption rules (hex/UUID/SRI-hash passes, non-ASCII token
//! delimiting, structured-identifier decomposition, trigger word-boundary
//! matching, the underscore-boundary asymmetry between bare trigger words and
//! the word `token`, and the adversarial-corpus rationale for why some
//! false positives are accepted) are documented in full in
//! `docs/api/secret_gate.md#module-level-detection-algorithm` — read that before
//! changing any detection or exemption logic in this file.
//!
//! The caller-visible block message (`SecretMatch`'s `Display` impl) also
//! carries actionable guidance (`block_guidance`) to split or reword the
//! flagged token.
//!
//! A production-corpus replay harness (`corpus_replay`, `#[ignore]`d, run via
//! `KHIVE_REPLAY_DB=<path> cargo test ... -- --ignored --nocapture`) measures
//! the detector's block rate against real note/entity content; see the
//! harness's own output for current numbers rather than a point-in-time count
//! here, which would drift as the corpus changes. A checked-in, sanitized
//! snapshot of that replay (per-detector block counts and sha256 digests of
//! blocked content, never the content itself) lives at
//! `tests/data/secret_gate_corpus_manifest.md`, generated by
//! `corpus_replay::generate_corpus_manifest`.
//! A replay that is identical before and after a change certifies preservation
//! on the corpus population only, never on the shape class the change opens;
//! that class needs its own before/after arms.

use crate::error::{RuntimeError, RuntimeResult};

mod entropy;
mod known_patterns;
mod masking;
mod submitted_atom_digest;

#[cfg(test)]
use entropy::TRIGGER_WINDOW;
use entropy::{
    check_entropy_heuristic, tokenize_entropy_tokens, EntropyScanContext, COMPOUND_TRIGGER_WORDS,
    ENTROPY_THRESHOLD, HEX_CREDENTIAL_LENGTHS, MAX_BRIDGE_FRAGMENTS, MAX_BRIDGE_GLUE_TOKENS,
    MIN_BRIDGE_FRAGMENT_LEN, MIN_ENTROPY_LEN, TRIGGER_WORDS,
};
use known_patterns::check_known_patterns;
#[cfg(doc)]
use known_patterns::find_url_userinfo;
#[cfg(test)]
use known_patterns::{find_prefix_token, is_filename_shaped_prefix_match, PREFIX_DETECTORS};
pub use masking::{
    bounded_masked_log_text, mask_bounded, mask_secrets, BoundedMask, MASK_WINDOW_CHARS,
};
#[cfg(test)]
use masking::{collect_mask_spans, MAX_LOG_TEXT_OUTPUT_CHARS, TRUNCATION_MARKER};
use masking::{extend_across_invisible_bridge, MAX_LOG_TEXT_MASK_INPUT_CHARS};

pub use submitted_atom_digest::masked_submitted_atom_digest_v1;

// ─── Public API ──────────────────────────────────────────────────────────────

/// Returned when a write would store credential-looking content.
///
/// Carries the detector name and a masked excerpt (`first6...Nchars`).  The
/// full candidate is never stored in the error.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SecretMatch {
    /// Human-readable name of the detector that fired.
    pub detector: &'static str,
    /// Canonical trigger from the matched context; known-prefix rules need none.
    pub trigger: Option<&'static str>,
    /// `first6...N` — the first 6 chars of the match followed by the total length.
    pub masked: String,
    /// Which record and field the match came from. `None` only where the
    /// caller scanned exactly one string and nothing else, so there is one
    /// candidate. A single-record verb that scans several fields still needs
    /// this: the writer sees one refusal and cannot tell whether it was the
    /// name, the content, a tag or a property that matched.
    pub location: Option<String>,
}

impl std::fmt::Display for SecretMatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "content matches secret pattern {}", self.detector)?;
        if let Some(trigger) = self.trigger {
            write!(f, " near '{trigger}'")?;
        }
        if let Some(location) = &self.location {
            write!(f, " in {location}")?;
        }
        write!(f, ". {}", block_guidance(self.detector))
    }
}

/// Actionable, caller-visible guidance for a hard block, keyed by detector
/// name. If the content genuinely is a credential, remove it. If it
/// is not — the common case for the detectors below, which key off SHAPE
/// near a trigger word rather than a known credential prefix — the fix is to
/// break up the flagged token so it no longer reads as one contiguous
/// high-entropy value: separate it from words like key/secret/auth/token with
/// a sentence or paragraph boundary, or use an explicit repository revision
/// reference for a source hash.
fn block_guidance(detector: &'static str) -> &'static str {
    match detector {
        "url-userinfo" => {
            "Placeholders in URL credential positions still match this pattern. \
             Replace the whole URL with an environment-variable name or config key, \
             or remove the entire user/password segment before writing."
        }
        "high-entropy-token"
        | "uuid-near-trigger"
        | "content-hash-near-trigger"
        | "hex-credential-token" => {
            "If this is a real credential, remove it before writing. If it is not \
             (e.g. a file path, UUID, or hash that happens to sit near a word like \
             key/secret/auth/token), put the candidate in a separate sentence or \
             paragraph from those words, or express a source hash as an explicit \
             commit/revision reference."
        }
        _ => {
            "If this is a real credential, remove it before writing; store secrets \
              in an env var or secrets manager instead."
        }
    }
}

/// Hard-block content from being written.
///
/// Returns `Err(RuntimeError::SecretDetected)` on the first match found, or
/// `Ok(())` if no secret pattern fires.
pub fn check(content: &str) -> RuntimeResult<()> {
    if let Some(m) = scan(content) {
        return Err(RuntimeError::SecretDetected(m));
    }
    Ok(())
}

/// Recursively scan a JSON value for credential-shaped strings.
///
/// Walks every string leaf (object values, array elements, nested objects).
/// Returns `Err(RuntimeError::SecretDetected)` on the first match found.
/// `None` / null / numeric / boolean JSON values are skipped.
pub fn check_json(value: &serde_json::Value) -> RuntimeResult<()> {
    scan_json_value(value)
}

/// Scan a string-tagged slice (entity/note tags).
///
/// Each tag string is scanned individually.
pub fn check_tags(tags: &[String]) -> RuntimeResult<()> {
    for tag in tags {
        check(tag)?;
    }
    Ok(())
}

/// Name the scope and field a refusal came from.
///
/// A batch verb scans each record and returns on the first refusal, so the
/// caller gets ONE error for N records. Without this the error names only the
/// matched text, which by construction is text the caller cannot find: it sits
/// in whichever sibling record refused, and every other record in the call is
/// rejected with it (khive #2605). Pass through anything that is not a gate
/// refusal unchanged — this adds identity, it does not reclassify.
///
/// `record` names the record the field belongs to, as the caller submitted it:
/// `entity`, `note`, `task`, `proposal`, `message`, indexed when it came from a
/// batch (`note[2]`). It answers where in the submitted payload the writer
/// should look, which is the question a refused writer actually asks.
pub fn locate<T>(result: RuntimeResult<T>, record: &str, field: &str) -> RuntimeResult<T> {
    result.map_err(|error| match error {
        RuntimeError::SecretDetected(matched) => RuntimeError::SecretDetected(SecretMatch {
            location: Some(format!("{record}.{field}")),
            ..matched
        }),
        other => other,
    })
}

/// `check` that names where it looked. `record` is the record noun the caller
/// submitted, indexed inside a batch; `field` is the field of it that was scanned.
pub fn check_at(content: &str, record: &str, field: &str) -> RuntimeResult<()> {
    locate(check(content), record, field)
}

/// `check_json` that names where it looked. The location is the field holding
/// the JSON, not the path of the string leaf that matched inside it.
pub fn check_json_at(value: &serde_json::Value, record: &str, field: &str) -> RuntimeResult<()> {
    locate(check_json(value), record, field)
}

/// `check_tags` that names where it looked.
pub fn check_tags_at(tags: &[String], record: &str, field: &str) -> RuntimeResult<()> {
    locate(check_tags(tags), record, field)
}

// ─── Reserved property keys ──────────────────────────────────────────────────

/// Top-level JSON property key reserved for runtime-owned exemption state.
///
/// No caller may create, replace, merge, or remove this key through any
/// properties-bearing write path — ADR-115 Amendment 1 §3. Reservation binds
/// unconditionally: the runtime does not yet stamp any record with this key
/// (the finalizer that would do so is a separate, later increment), so no
/// caller-supplied occurrence of it can ever be a legitimate echo of
/// persisted state. Only the exact top-level key is reserved; the same
/// spelling nested inside an object *value* is ordinary content and remains
/// subject to [`check_json`], never a posture mutation.
pub const RESERVED_SECRET_GATE_KEY: &str = "khive:secret_gate";
pub const RESERVED_WEB_RECEIPT_KEY: &str = "khive:web_receipt";
pub const WEB_RECEIPT_PROVENANCE_VALUE: &str = "v1";

/// Reject a caller-supplied top-level `khive:secret_gate` property key.
///
/// Call this before any diff, merge, or storage preparation touches
/// caller-supplied `properties` on any properties-bearing write path —
/// create, patch update, or full replace. Returns `Ok(())` when `properties`
/// is absent, is not a JSON object, or does not name the reserved key at the
/// top level.
///
/// This is the shared validator for both the ADR-115 reservation and web
/// receipt provenance. Every properties-bearing generic write path calls it
/// before a merge or full-row replacement.
pub fn reject_reserved_secret_gate_property(
    properties: Option<&serde_json::Value>,
) -> RuntimeResult<()> {
    if let Some(serde_json::Value::Object(map)) = properties {
        if map.contains_key(RESERVED_SECRET_GATE_KEY) {
            return Err(RuntimeError::InvalidInput(format!(
                "property key `{RESERVED_SECRET_GATE_KEY}` is runtime-owned and cannot be \
                 created, replaced, merged, or removed by callers"
            )));
        }
        if map.contains_key(RESERVED_WEB_RECEIPT_KEY) {
            return Err(RuntimeError::InvalidInput(format!(
                "property key `{RESERVED_WEB_RECEIPT_KEY}` is web-pack-owned and cannot be \
                 created, replaced, merged, or removed by callers"
            )));
        }
    }
    Ok(())
}

fn scan_json_value(value: &serde_json::Value) -> RuntimeResult<()> {
    match value {
        serde_json::Value::String(s) => check(s),
        serde_json::Value::Array(arr) => {
            for v in arr {
                scan_json_value(v)?;
            }
            Ok(())
        }
        serde_json::Value::Object(map) => {
            for (k, v) in map {
                // Scan both the key (a credential can appear as a JSON key name)
                // and the value recursively.
                check(k)?;
                scan_json_value(v)?;
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

// ─── Scanner ─────────────────────────────────────────────────────────────────

/// Marker substituted for a detected secret span by [`mask_secrets`].
const REDACTION_MARKER: &str = "***MASKED***";

/// Maximum cumulative bytes revisited by the per-pass detector sweeps while masking
/// one input. Entropy tokens are materialized once, but resuming inside a token
/// rebuilds its member candidates and revisits their context, so that token's
/// full prefix is also charged. This permits two full-size passes over the 1 MiB
/// ASCII log-input case; the first pass is always allowed for larger or multibyte
/// callers. Once exhausted, the remainder is redacted wholesale.
const MAX_MASK_SCAN_WORK_BYTES: usize = MAX_LOG_TEXT_MASK_INPUT_CHARS * 2;

#[cfg(test)]
thread_local! {
    static ENTROPY_TOKENIZATION_COUNT: std::cell::Cell<usize> = const { std::cell::Cell::new(0) };
}

/// Return the LEFTMOST secret in `text` as `(matched_slice, detector)`.
///
/// The matched slice borrows from `text`, so the caller can recover its byte
/// span via pointer arithmetic — this is what lets [`mask_secrets`] redact in
/// place while [`scan`] only needs the masked excerpt.
///
/// "Leftmost" (smallest start offset), NOT first-by-detector-priority, is the
/// load-bearing contract: [`mask_secrets`] copies the text *before* each match
/// verbatim, so a non-leftmost match would leak an earlier secret detected by a
/// lower-priority detector (e.g. an `sk-ant-` key sitting to the left of a
/// `ghp_` token). Both detector layers are folded through [`keep_leftmost`].
#[cfg(test)]
fn scan_match(text: &str) -> Option<(&str, &'static str)> {
    let context = EntropyScanContext::new(text);
    scan_from(text, 0, &context)
}

/// Like [`scan_match`], but only returns secrets whose span starts at or after
/// `from`, while still evaluating Layer-2 trigger context against the FULL
/// `text`. [`mask_secrets`] calls this with an advancing `from` so that an
/// entropy token is detected even when its only trigger word sits to the left of
/// an already-redacted earlier secret. Layer-1 known patterns are context-free,
/// so scanning the `&text[from..]` suffix is equivalent; offsets recovered via
/// pointer arithmetic against the original `text` base stay absolute. The
/// pre-tokenized entropy view is shared by all passes.
fn scan_from<'a>(
    text: &'a str,
    from: usize,
    context: &EntropyScanContext<'a>,
) -> Option<(&'a str, &'static str)> {
    scan_from_with_trigger(text, from, context).map(|(slice, detector, _)| (slice, detector))
}

fn scan_from_with_trigger<'a>(
    text: &'a str,
    from: usize,
    context: &EntropyScanContext<'a>,
) -> Option<(&'a str, &'static str, Option<&'static str>)> {
    let mut best =
        check_known_patterns(&text[from..]).map(|(slice, detector)| (slice, detector, None));
    if let Some(candidate) = check_entropy_heuristic(text, from, context) {
        if best
            .as_ref()
            .is_none_or(|current| candidate.0.as_ptr() < current.0.as_ptr())
        {
            best = Some(candidate);
        }
    }
    best
}

/// Replace `best` with `cand` when `cand` starts earlier in the original text
/// (`base` is the start address of that text). On a tie the incumbent wins, so
/// callers offer more-specific detectors first. This is what makes
/// [`check_known_patterns`] and [`scan_match`] return the leftmost secret span
/// rather than the first detector that happens to match anywhere.
fn keep_leftmost<'a>(
    best: &mut Option<(&'a str, &'static str)>,
    cand: Option<(&'a str, &'static str)>,
    base: usize,
) {
    if let Some((slice, name)) = cand {
        let start = slice.as_ptr() as usize - base;
        let replace = match *best {
            Some((incumbent, _)) => start < (incumbent.as_ptr() as usize - base),
            None => true,
        };
        if replace {
            *best = Some((slice, name));
        }
    }
}

/// Return the first `SecretMatch` found in `text`, or `None`.
fn scan(text: &str) -> Option<SecretMatch> {
    let context = EntropyScanContext::new(text);
    scan_from_with_trigger(text, 0, &context).map(|(slice, detector, trigger)| {
        let mut matched = build_match(detector, slice);
        matched.trigger = trigger;
        matched
    })
}

/// A named redact-not-block surface whose contract is intentionally separate
/// from manifest-backed write admission (ADR-115 Amendment 2).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RedactionSurface {
    /// Git ingestion stores only masked commit, issue, and pull-request text.
    GitIngest,
    /// Session mirroring stores only masked `text` and `raw` projections.
    SessionMirror,
    /// MCP diagnostics are bounded caller-visible transport data, not records.
    McpDiagnostic,
    /// The kg `scan` verb's masked preview: caller-visible, never stored.
    GateProbe,
}

/// Whether a redaction surface can consume a secret-gate exemption.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RedactionSurfaceMode {
    /// Always apply the canonical masker; never synthesize a stamp or event.
    PermanentMaskOnly,
}

/// Machine-readable contract for a named redaction surface.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RedactionSurfaceContract {
    pub mode: RedactionSurfaceMode,
    /// Durable target containing the masked result, if this is a write surface.
    pub final_stored_target: Option<&'static str>,
    /// Reserved stamp location; absent for permanent mask-only surfaces.
    pub stamp_property: Option<&'static str>,
    /// Atomic exemption-success event; absent when admission cannot occur.
    pub atomic_success_event: Option<&'static str>,
}

/// Final stored target for [`RedactionSurface::GitIngest`] — see
/// [`redaction_surface_contract`].
pub const GIT_INGEST_STORED_TARGET: &str = "final git-ingest entity/note fields";

/// Final stored target for [`RedactionSurface::SessionMirror`] — see
/// [`redaction_surface_contract`]. Names every column the session mirror
/// writes a masked provider-export projection into, not just the message
/// body columns. `cwd`/`git_branch` live only on `sessions`, keyed per
/// session — `session_messages` carries no such columns of its own (see the
/// `session_messages` DDL in `khive-pack-session`).
pub const SESSION_MIRROR_STORED_TARGET: &str =
    "session_messages.text, session_messages.raw, sessions.cwd, sessions.git_branch, \
     and sessions.slug";

/// Return the closed contract for a named redact-not-block surface.
pub const fn redaction_surface_contract(surface: RedactionSurface) -> RedactionSurfaceContract {
    let final_stored_target = match surface {
        RedactionSurface::GitIngest => Some(GIT_INGEST_STORED_TARGET),
        RedactionSurface::SessionMirror => Some(SESSION_MIRROR_STORED_TARGET),
        RedactionSurface::McpDiagnostic | RedactionSurface::GateProbe => None,
    };

    RedactionSurfaceContract {
        mode: RedactionSurfaceMode::PermanentMaskOnly,
        final_stored_target,
        stamp_property: None,
        atomic_success_event: None,
    }
}

/// Apply the canonical detector to a named permanent mask-only surface.
///
/// This wrapper makes the non-admission decision executable at each call site:
/// it has no manifest input, cannot return an exemption outcome, and cannot
/// synthesize the runtime-owned `khive:secret_gate` property or success event.
pub fn mask_for_redaction_surface(
    surface: RedactionSurface,
    text: &str,
) -> std::borrow::Cow<'_, str> {
    match redaction_surface_contract(surface).mode {
        RedactionSurfaceMode::PermanentMaskOnly => mask_secrets(text),
    }
}

/// `true` when every byte of `run` is an ASCII hex digit. The
/// no-minimum-length, no-`0x`-prefix building block for
/// [`normalized_hex_credential_span`]'s intra-token run decomposition.
/// Unlike [`is_pure_hex`] this has no 8-char floor of its own — a legitimate
/// credential split across separators can leave a shorter individual run
/// that still must sum correctly with its neighbors.
fn is_hex_run(run: &str) -> bool {
    !run.is_empty() && run.bytes().all(|b| b.is_ascii_hexdigit())
}

const VCS_MARKERS: &[&str] = &["commit", "revision", "rev", "sha"];

/// Marker-word form of a VCS reference: `raw_token` is itself a bare marker
/// and the next token in `text` is a 40-hex value.
fn is_vcs_marker_before_hex(text: &str, raw_token: &str) -> bool {
    let token = wrapper_strip_repeated(raw_token);
    let marker = strip_delimiters(token);
    if !VCS_MARKERS
        .iter()
        .any(|candidate| marker.eq_ignore_ascii_case(candidate))
    {
        return false;
    }
    let raw_offset = raw_token.as_ptr() as usize - text.as_ptr() as usize;
    let next = text[raw_offset + raw_token.len()..].trim_start();
    let next = wrapper_strip_repeated(extract_token(next));
    next.len() == 40 && next.bytes().all(|b| b.is_ascii_hexdigit())
}

fn is_git_revision_reference(text: &str, token_offset: usize, raw_token: &str) -> bool {
    const MARKERS: &[&str] = VCS_MARKERS;

    let token = wrapper_strip_repeated(raw_token);
    if is_vcs_marker_before_hex(text, raw_token) {
        return true;
    }

    if token.len() == 40 && token.bytes().all(|b| b.is_ascii_hexdigit()) {
        let marker = trailing_identifier(&text[..token_offset]);
        return MARKERS
            .iter()
            .any(|candidate| marker.eq_ignore_ascii_case(candidate));
    }

    let Some((label, value)) = token.rsplit_once(':') else {
        return false;
    };
    let label = wrapper_strip_repeated(label);
    let value = wrapper_strip_repeated(value);
    MARKERS
        .iter()
        .any(|candidate| label.eq_ignore_ascii_case(candidate))
        && value.len() == 40
        && value.bytes().all(|b| b.is_ascii_hexdigit())
}

fn is_exact_hex_revision(value: &str) -> bool {
    value.len() == 40 && value.bytes().all(|byte| byte.is_ascii_hexdigit())
}

/// Repository-native revision coordinates embedded in a URL/HTML token.
///
/// This intentionally recognizes only exact 40-hex revisions after a
/// canonical repository path marker, plus an exact `href=<40hex>` target.
/// Arbitrary query values, prefixes, and credential-length hex elsewhere in
/// markup remain subject to the normal detector.
fn is_repository_revision_reference(raw_token: &str) -> bool {
    let token = wrapper_strip_repeated(raw_token);
    let low = token.to_ascii_lowercase();

    for marker in ["/blob/", "/tree/", "/commit/", "/commits/"] {
        let mut from = 0usize;
        while let Some(relative) = low[from..].find(marker) {
            let value_start = from + relative + marker.len();
            let remainder = &token[value_start..];
            let value_end = remainder
                .bytes()
                .position(|byte| !byte.is_ascii_hexdigit())
                .unwrap_or(remainder.len());
            if is_exact_hex_revision(&remainder[..value_end]) {
                return true;
            }
            from = value_start.min(low.len());
            if from == low.len() {
                break;
            }
        }
    }

    for (prefix, quote) in [("href=\"", '"'), ("href='", '\'')] {
        if let Some(start) = low.find(prefix) {
            let value = &token[start + prefix.len()..];
            if let Some(end) = value.find(quote) {
                if is_exact_hex_revision(&value[..end]) {
                    return true;
                }
            }
        }
    }

    false
}

fn trailing_identifier(text: &str) -> &str {
    let trimmed = text.trim_end_matches(|c: char| !c.is_ascii_alphanumeric() && c != '_');
    trimmed
        .rsplit(|c: char| !c.is_ascii_alphanumeric() && c != '_')
        .next()
        .unwrap_or_default()
}

/// Return whether the identifier immediately preceding a candidate is a
/// credential label. This deliberately does not walk through narrative prose:
/// notation such as `key estimate uses \\operatorname{softmax}` contains a
/// trigger word, but does not assign the LaTeX fragment to that word.
fn has_immediate_credential_label(text: &str, token_offset: usize) -> bool {
    let before = text[..token_offset].trim_end();
    let before = before
        .strip_suffix(':')
        .or_else(|| before.strip_suffix('='))
        .unwrap_or(before);
    let label = trailing_identifier(before).to_ascii_lowercase();

    label == "token"
        || COMPOUND_TRIGGER_WORDS
            .iter()
            .any(|trigger| label.contains(trigger))
        || TRIGGER_WORDS
            .iter()
            .any(|trigger| contains_bounded_word(&label, trigger))
}

/// A repository revision URL/href is exempt from broad trigger proximity,
/// but never from a direct credential label. When a value separator is
/// present immediately before the reference, only its actual field label is
/// authoritative: narrative shapes such as `key-scoped source citation:`
/// must not turn the earlier adjective into the citation value's label.
fn has_direct_repository_credential_label_with_inline(
    text: &str,
    token_offset: usize,
    inline_trigger: bool,
) -> bool {
    if inline_trigger {
        return true;
    }
    let before = text[..token_offset].trim_end();
    if before.ends_with(':') || before.ends_with('=') {
        return has_immediate_credential_label(text, token_offset);
    }
    has_clause_credential_label_with_inline(
        text,
        token_offset,
        false,
        ClauseValueKind::VcsReference,
    )
}

/// Words the clause walk in [`has_clause_credential_label_with_inline`] steps over when
/// searching backwards for a credential label. Connectors are the words that
/// commonly sit between a label and its value in natural assignment prose
/// ("api key value is X", "the token was X"); the VCS coordinate markers are
/// included so the marker itself cannot shield an earlier label from the
/// walk ("api key value is commit <hex>"); prepositions, determiners, and
/// possessives are the glue of noun-compound label qualifiers ("api key for
/// our production deploy: X") and carry no content of their own.
const LABEL_CLAUSE_SKIP_WORDS: &[&str] = &[
    "commit",
    "revision",
    "rev",
    "sha",
    "is",
    "was",
    "are",
    "were",
    "be",
    "been",
    "being",
    "value",
    "values",
    "the",
    "a",
    "an",
    "this",
    "that",
    "it",
    "its",
    "as",
    "here",
    "now",
    "currently",
    "equals",
    "for",
    "of",
    "to",
    "in",
    "on",
    "at",
    "by",
    "with",
    "from",
    "per",
    "and",
    "or",
    "our",
    "my",
    "your",
    "their",
];

/// Maximum identifiers the clause walk examines. Bounds the scan cost to one
/// short assignment clause. Exhausting the budget is NOT evidence of absence:
/// when a value delimiter was crossed, running out of steps fails CLOSED
/// (treated as credential-labeled) — a truncated scan cannot prove the clause
/// is unlabeled, and any exhaustion-fails-open rule re-admits the labeled
/// value bypass one natural word past the budget. Sized so a label separated
/// from its value by connectors plus a dotted version qualifier ("api key
/// v1.2 value is commit <hex>" — the version costs two identifier steps)
/// stays in range without exhaustion.
const LABEL_CLAUSE_WALK_LIMIT: usize = 8;

/// File-path candidates may walk across at most this many content identifiers
/// without a `:`/`=` delimiter. Two reaches the direct-label shapes that need
/// protection (`auth scanner found <path>`) while keeping the walk local.
const FILE_PATH_NO_DELIMITER_CONTENT_LIMIT: usize = 2;

/// The two narrow trigger-context exemptions need different no-delimiter
/// behavior. VCS coordinates preserve the strict prose guard that keeps
/// `the key changes are in commit <sha>` readable; file paths admit the
/// bounded bridge above so a short label cannot disguise a credential value.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum ClauseValueKind {
    VcsReference,
    FilePath,
}

/// End offset of a sentence/paragraph boundary beginning at `index`.
///
/// A single newline remains intra-sentence so natural credential assignments
/// such as `api key:\n<value>` stay protected. Blank lines, clause-ending
/// punctuation, and a period followed by a non-alphanumeric byte end the
/// surrounding trigger context. The period rule deliberately keeps `v1.2`
/// intra-sentence.
fn sentence_boundary_end_at(bytes: &[u8], index: usize) -> Option<usize> {
    match bytes.get(index).copied()? {
        b';' | b'!' | b'?' => Some(index + 1),
        b'.' if bytes
            .get(index + 1)
            .is_some_and(|next| !next.is_ascii_alphanumeric()) =>
        {
            Some(index + 1)
        }
        b'\n' if bytes.get(index + 1) == Some(&b'\n') => Some(index + 2),
        b'\r'
            if bytes
                .get(index..index + 4)
                .is_some_and(|window| window == b"\r\n\r\n") =>
        {
            Some(index + 4)
        }
        _ => None,
    }
}

/// Context after the final sentence boundary in `text`.
fn after_last_sentence_boundary(text: &str) -> &str {
    let bytes = text.as_bytes();
    let mut start = 0usize;
    for index in 0..bytes.len() {
        if let Some(end) = sentence_boundary_end_at(bytes, index) {
            start = end;
        }
    }
    &text[start..]
}

/// Context before the first sentence boundary in `text`.
fn before_first_sentence_boundary(text: &str) -> &str {
    let bytes = text.as_bytes();
    for index in 0..bytes.len() {
        if sentence_boundary_end_at(bytes, index).is_some() {
            return &text[..index];
        }
    }
    text
}

/// Sentence/paragraph boundary inside a clause-walk gap. `;`, `!`, `?`, and
/// blank lines always end the clause. `.` ends it only when it is not
/// immediately followed by an alphanumeric character: a dot tight between
/// identifier fragments ("v1.2") is intra-token punctuation, while a dot at
/// the end of the gap abuts the next identifier (gaps end where the adjacent
/// identifier begins) and is likewise intra-token.
fn gap_has_sentence_boundary(gap: &str) -> bool {
    let bytes = gap.as_bytes();
    (0..bytes.len()).any(|index| sentence_boundary_end_at(bytes, index).is_some())
}

/// Version-shaped identifier fragment ("2", "v1", "12") — the pieces a dotted
/// version qualifier like `v1.2` splits into under identifier extraction.
/// Treated as connector material so a versioned label ("api key v1.2 value
/// is …") stays reachable.
fn is_version_fragment(word: &str) -> bool {
    let digits = word
        .strip_prefix('v')
        .or_else(|| word.strip_prefix('V'))
        .unwrap_or(word);
    !digits.is_empty() && digits.bytes().all(|b| b.is_ascii_digit())
}

/// Hex-run identifier long enough to be credential material rather than a
/// word ("0123456789abcdef01234567"). Treated as connector material by the
/// clause walk: a separator-split payload fragment sitting between the
/// candidate value and its label is value material, not a label word that
/// ends the clause.
fn is_hex_fragment_word(word: &str) -> bool {
    word.len() >= 12 && word.bytes().all(|b| b.is_ascii_hexdigit())
}

/// Allocation-free case-insensitive substring search for ASCII identifiers.
fn contains_ascii_case_insensitive(haystack: &str, needle: &str) -> bool {
    haystack
        .as_bytes()
        .windows(needle.len())
        .any(|window| window.eq_ignore_ascii_case(needle.as_bytes()))
}

/// A trailing identifier can contain only ASCII alphanumerics and `_`, so
/// splitting on `_` exactly preserves the bare-trigger boundary rule used by
/// [`contains_bounded_word`] without allocating a lowercase copy.
fn clause_label_has_credential_trigger(label: &str) -> bool {
    label.eq_ignore_ascii_case("token")
        || COMPOUND_TRIGGER_WORDS
            .iter()
            .any(|trigger| contains_ascii_case_insensitive(label, trigger))
        || label.split('_').any(|part| {
            TRIGGER_WORDS
                .iter()
                .any(|trigger| part.eq_ignore_ascii_case(trigger))
        })
}

fn is_label_clause_skip_word(label: &str) -> bool {
    LABEL_CLAUSE_SKIP_WORDS
        .iter()
        .any(|word| label.eq_ignore_ascii_case(word))
}

/// Words ending in the byte sequence `ed` are only a cheap proxy for a
/// regular English participle. Keep known lexical false matches explicit so
/// a noun such as `hundred` cannot become evidence that a credential label is
/// merely narrative prose. Irregular forms such as `found` deliberately do
/// not qualify: they must not shield `api key found <value>`.
fn is_clause_narrative_participle(label: &str) -> bool {
    const NON_PARTICIPLE_ED_WORDS: &[&str] = &["hundred"];

    label.len() >= 5
        && label
            .get(label.len().saturating_sub(2)..)
            .is_some_and(|suffix| suffix.eq_ignore_ascii_case("ed"))
        && !NON_PARTICIPLE_ED_WORDS
            .iter()
            .any(|word| label.eq_ignore_ascii_case(word))
}

/// Cheap regular-gerund proxy used only after the no-delimiter file-path walk
/// has crossed an explicit `in` on the value side (`api_key handling in
/// <path>`). Adjacency alone is never narrative evidence: `api key handling
/// <value>` must keep walking to the direct credential label.
fn is_clause_narrative_gerund(label: &str) -> bool {
    label.len() >= 6
        && label
            .get(label.len().saturating_sub(3)..)
            .is_some_and(|suffix| suffix.eq_ignore_ascii_case("ing"))
}

/// `true` when the candidate token sits in credential-value syntax: an inline
/// credential shape on the token itself, or a credential label reachable by
/// walking backwards through the current clause. The walk steps over
/// [`LABEL_CLAUSE_SKIP_WORDS`], version fragments, and long hex fragments,
/// and stops at a sentence/paragraph boundary (see
/// [`gap_has_sentence_boundary`]) — a label on the far side of a boundary is
/// prose context, not this value's label. Crossing a value delimiter (`:` or
/// `=`, including one attached to a VCS marker: "deploy sha: <hex>" is still
/// assignment syntax) additionally lets the walk step over content words
/// outside those sets, bounded only by [`LABEL_CLAUSE_WALK_LIMIT`], the
/// sentence boundary, and the past-participle stop: "label with qualifiers:
/// value" names the value regardless of how many qualifier nouns the label
/// carries ("api key for production deploy: X", "api key for shared
/// encrypted deploy: X"). A per-clause content-word cap was tried here and
/// removed — any cap re-admits the labeled-value bypass one natural
/// qualifier past the cap. For the same reason, exhausting the walk budget
/// after crossing a delimiter fails CLOSED: the clause is assignment-shaped
/// and its head was never scanned, so it is treated as credential-labeled.
/// A regular past-participle content word ("flagged", "introduced") ends the walk —
/// verb-phrase prose narrates an action on the value rather than labeling it
/// ("the auth scanner flagged this file: <path>", "one extra token was
/// introduced by sha: <hex>"). Coordinating conjunctions are transparent to
/// that position test — "shared and encrypted deploy" keeps both participles
/// in adjective position. Without a delimiter, VCS references step over only
/// the closed connector sets, preserving ordinary prose such as "the key
/// changes are in commit <hex>". File paths additionally step over at most
/// [`FILE_PATH_NO_DELIMITER_CONTENT_LIMIT`] content words, closing direct
/// label shapes such as "auth scanner found <path>" without broadening the
/// VCS tier.
fn has_clause_credential_label_with_inline(
    text: &str,
    token_offset: usize,
    inline_trigger: bool,
    value_kind: ClauseValueKind,
) -> bool {
    if inline_trigger {
        return true;
    }

    let mut rest = &text[..token_offset];
    let mut crossed_value_delimiter = false;
    let mut no_delimiter_content_words = 0usize;
    // Whether the previously processed identifier (the one nearer the value)
    // was the literal preposition `in`. This starts false deliberately:
    // adjacency to the value must not make a gerund narrative evidence.
    let mut arrived_through_in_preposition = false;
    // Whether the previously processed identifier (the one nearer the value)
    // was connector material. Starts true: step 0 is adjacent to the value or
    // its delimiter.
    let mut arrived_through_connector = true;
    for step in 0..LABEL_CLAUSE_WALK_LIMIT {
        let label = trailing_identifier(rest);
        if label.is_empty() {
            return false;
        }
        let gap = &rest[label.as_ptr() as usize - rest.as_ptr() as usize + label.len()..];
        if step > 0 && gap_has_sentence_boundary(gap) {
            return false;
        }
        if gap.contains([':', '=']) {
            crossed_value_delimiter = true;
        }
        if clause_label_has_credential_trigger(label) {
            return true;
        }
        let skippable = is_label_clause_skip_word(label)
            || is_version_fragment(label)
            || is_hex_fragment_word(label);
        if !skippable {
            // This barrier applies to delimiter-bearing clauses and to the
            // bounded file-path bridge. It intentionally recognizes regular
            // `-ed` forms only: `found` is a bridge word, not a narrative
            // shield for a direct credential label.
            let no_delimiter_file_path_narrative = !crossed_value_delimiter
                && value_kind == ClauseValueKind::FilePath
                && arrived_through_in_preposition
                && is_clause_narrative_gerund(label);
            // Delimiter-bearing clauses and VCS coordinates preserve their
            // existing direct-participle semantics. A no-delimiter file path
            // must first process real value-side context: the synthetic
            // initial connector state alone cannot let `api key leaked
            // <value>` stop before reaching the trigger.
            let regular_participle_narrative = is_clause_narrative_participle(label)
                && (crossed_value_delimiter || value_kind != ClauseValueKind::FilePath || step > 0);
            if arrived_through_connector
                && (regular_participle_narrative || no_delimiter_file_path_narrative)
            {
                return false;
            }
            if !crossed_value_delimiter {
                if value_kind != ClauseValueKind::FilePath
                    || no_delimiter_content_words >= FILE_PATH_NO_DELIMITER_CONTENT_LIMIT
                {
                    return false;
                }
                no_delimiter_content_words += 1;
            }
        }
        // Coordinating conjunctions are transparent to participle-position
        // classification: in "shared and encrypted deploy" the coordination
        // as a whole is followed by a content noun, so "shared" is still an
        // adjective — the conjunction preserves the arrived state instead of
        // marking connector position.
        if !label.eq_ignore_ascii_case("and") && !label.eq_ignore_ascii_case("or") {
            arrived_through_connector = skippable;
        }
        arrived_through_in_preposition = label.eq_ignore_ascii_case("in");
        let start = label.as_ptr() as usize - rest.as_ptr() as usize;
        rest = &rest[..start];
    }
    // Budget exhausted. A clause that crossed a value delimiter and ran out
    // of steps without a sentence boundary or verb-position participle is
    // assignment-shaped with an unscanned head — fail closed rather than let
    // clause length launder a labeled credential into the exemptions.
    crossed_value_delimiter
}

fn is_plausible_file_path(token: &str) -> bool {
    let token = token.trim_start_matches(|c: char| {
        matches!(
            c,
            '"' | '\'' | '`' | '(' | ')' | '[' | ']' | '{' | '}' | ',' | ';'
        )
    });
    let token = token.trim_end_matches(|c: char| {
        matches!(
            c,
            '"' | '\'' | '`' | '(' | ')' | '[' | ']' | '{' | '}' | ',' | ';' | '.'
        )
    });
    let path = if let Some(angle_path) = token.strip_prefix('<') {
        let Some(close) = angle_path.rfind('>') else {
            return false;
        };
        if !is_line_location_suffix(&angle_path[close + 1..]) {
            return false;
        }
        &angle_path[..close]
    } else if let Some((path, suffix)) = token.rsplit_once(':') {
        if is_line_location_suffix(suffix) {
            path
        } else {
            token
        }
    } else {
        token
    };

    if path.contains("://")
        || !path.contains('/')
        || !path
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'/' | b'.' | b'_' | b'-' | b'~'))
    {
        return false;
    }

    let segment_count = path
        .split('/')
        .filter(|segment| !segment.is_empty())
        .count();
    segment_count >= 2 || (path.starts_with('/') && segment_count == 1)
}

/// Narrow high-entropy exemption for mathematical notation (#1988).
///
/// A fragment needs both a LaTeX control sequence and several structural
/// delimiters. Any embedded credential-length hex or independently
/// high-entropy alphanumeric run disables the exemption, so wrapping an
/// opaque value in `\texttt{...}` does not launder it.
fn is_latex_fragment_without_credential_run(token: &str) -> bool {
    let bytes = token.as_bytes();
    let has_control_sequence = bytes
        .windows(2)
        .any(|pair| pair[0] == b'\\' && pair[1].is_ascii_alphabetic());
    let structural_count = bytes
        .iter()
        .filter(|byte| matches!(byte, b'\\' | b'{' | b'}' | b'^' | b'_'))
        .count();
    if !has_control_sequence || structural_count < 3 {
        return false;
    }

    if normalized_hex_credential_span(token).is_some() {
        return false;
    }

    !token
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|run| run.len() >= MIN_ENTROPY_LEN)
        .any(|run| shannon_entropy(run.as_bytes()) >= ENTROPY_THRESHOLD)
}

/// A SHA-256 value is admitted only with a nearby checksum designation, not
/// with a credential field that merely happens to describe its encoding.
fn is_labeled_sha256_digest(text: &str, token_offset: usize, token: &str) -> bool {
    if token.len() != 64 || !token.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return false;
    }
    let before = text[..token_offset]
        .trim_end_matches(|ch: char| ch.is_ascii_whitespace() || matches!(ch, ':' | '='));
    let marker = ["sha256 key digest", "sha256 digest", "sha256"]
        .into_iter()
        .find(|marker| {
            before
                .get(before.len().saturating_sub(marker.len())..)
                .is_some_and(|tail| tail.eq_ignore_ascii_case(marker))
        });
    let Some(marker) = marker else {
        return false;
    };
    let marker_start = before.len() - marker.len();
    if marker_start > 0
        && text[..marker_start]
            .chars()
            .next_back()
            .is_some_and(|ch| ch.is_ascii_alphanumeric() || ch == '_')
    {
        return false;
    }
    !has_clause_credential_label_with_inline(text, marker_start, false, ClauseValueKind::FilePath)
}

/// Inline Rust call references have syntax that an opaque credential does not:
/// backticks, a qualified symbol, and an empty argument list. Arguments are
/// excluded because their values would otherwise become part of the exemption.
fn is_prose_code_reference(member: &str, token: &str) -> bool {
    let Some(code) = member.strip_prefix('`').and_then(|s| s.strip_suffix('`')) else {
        return false;
    };
    if code != token || !code.ends_with("()") {
        return false;
    }
    let Some((owner, method)) = code[..code.len() - 2].split_once("::") else {
        return false;
    };
    owner
        .as_bytes()
        .first()
        .is_some_and(|b| b.is_ascii_alphabetic())
        && owner
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_')
        && method
            .as_bytes()
            .first()
            .is_some_and(|b| b.is_ascii_alphabetic())
        && method
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'_' | b':' | b'<' | b'>'))
        && !method.contains("::")
}

/// Uppercase environment references are names, not values, when their final
/// component names a conventional non-secret field. The run checks above
/// still refuse any credential-shaped component inside the name.
fn is_environment_name(token: &str) -> bool {
    let mut components = token.split('_');
    let Some(first) = components.next() else {
        return false;
    };
    if first.is_empty() || !first.bytes().all(|b| b.is_ascii_uppercase()) {
        return false;
    }
    let mut count = 0;
    let mut last = "";
    for part in components {
        if part.is_empty()
            || part.len() > 16
            || !part
                .bytes()
                .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit())
        {
            return false;
        }
        count += 1;
        last = part;
    }
    count >= 3 && matches!(last, "PATH" | "FILE" | "NAME" | "TTL")
}

/// Closed, familiar math commands keep this exemption on notation rather
/// than arbitrary backslash-prefixed strings.
fn is_latex_prose_macro(token: &str) -> bool {
    [
        "\\mathsf{",
        "\\mathbf{",
        "\\mathcal{",
        "\\mathrm{",
        "\\operatorname{",
    ]
    .iter()
    .any(|prefix| token.starts_with(prefix))
        && is_latex_fragment_without_credential_run(token)
}

/// Recognize two unambiguous AWS resource address forms. The resource path
/// is restricted to short name segments; an embedded long credential run is
/// refused before this predicate is reached.
fn is_aws_resource_name(token: &str) -> bool {
    let mut parts = token.splitn(6, ':');
    let (Some("arn"), Some("aws"), Some(service), Some(region), Some(account), Some(resource)) = (
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
        parts.next(),
    ) else {
        return false;
    };
    let valid_resource = !resource.is_empty()
        && resource.split('/').all(|segment| {
            !segment.is_empty()
                && segment.len() <= 24
                && segment
                    .bytes()
                    .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'-' | b'_' | b'.'))
        });
    valid_resource
        && ((service == "s3" && region.is_empty() && account.is_empty())
            || (service == "iam"
                && region.is_empty()
                && account.len() == 12
                && account.bytes().all(|b| b.is_ascii_digit())
                && (resource.starts_with("role/") || resource.starts_with("policy/"))))
}

fn is_line_location_suffix(suffix: &str) -> bool {
    if suffix.is_empty() {
        return true;
    }
    let suffix = suffix.strip_prefix(':').unwrap_or(suffix);
    let suffix = suffix.strip_prefix('~').unwrap_or(suffix);
    let mut parts = suffix.split('-');
    let Some(start) = parts.next() else {
        return false;
    };
    !start.is_empty()
        && start.bytes().all(|b| b.is_ascii_digit())
        && parts
            .next()
            .is_none_or(|end| !end.is_empty() && end.bytes().all(|b| b.is_ascii_digit()))
        && parts.next().is_none()
}

/// The raw span whose consecutive pure-hex runs — splitting on every
/// non-alphanumeric character and dropping the separators for length
/// accounting — reach one of [`HEX_CREDENTIAL_LENGTHS`].
///
/// Closes the separator-dilution bypass (#1062) where a credential-length
/// hex payload is spread across multiple runs each individually below
/// [`MIN_ENTROPY_LEN`]: `0123456789abcdef0123/456789abcdef01234567` is two
/// 20-char hex runs that never individually reach 24 chars or a
/// credential-length boundary, but normalize to one 40-char hex sequence.
/// A non-hex, non-empty run resets the running sum — this only bridges
/// ADJACENT hex runs, not hex fragments scattered across unrelated filler.
fn normalized_hex_credential_span(token: &str) -> Option<&str> {
    let mut concatenated_len = 0usize;
    let mut span_start = 0usize;
    for run in token.split(|c: char| !c.is_ascii_alphanumeric()) {
        if run.is_empty() {
            continue;
        }
        if is_hex_run(run) {
            let run_start = run.as_ptr() as usize - token.as_ptr() as usize;
            if concatenated_len == 0 {
                span_start = run_start;
            }
            concatenated_len += run.len();
            if HEX_CREDENTIAL_LENGTHS.contains(&concatenated_len) {
                return Some(&token[span_start..run_start + run.len()]);
            }
        } else {
            concatenated_len = 0;
        }
    }
    None
}

/// `true` when the gap `text[gap_start..gap_end]` between two adjacent
/// tokenizer tokens holds no ASCII alphanumeric character — the shape a
/// tokenizer-delimiting separator (ASCII whitespace, or a non-ASCII
/// character such as U+200B; see the tokenizer comment in
/// [`check_entropy_heuristic`]) leaves behind when it splits one credential
/// payload into two tokens. Deliberately UNBOUNDED on gap byte length
/// (#1062: a byte-length bound here is defeated outright by
/// repeating the delimiter character) — [`bridge_fragment_chain`] is what
/// keeps the overall reconstruction bounded, via [`MAX_BRIDGE_FRAGMENTS`],
/// not this check. This still never bridges tokens separated by a genuine
/// word or sentence: any real word in the gap contains an ASCII alphanumeric
/// character and fails the check immediately.
fn adjacent_gap_is_bridgeable(text: &str, gap_start: usize, gap_end: usize) -> bool {
    gap_end >= gap_start && !text[gap_start..gap_end].contains(|c: char| c.is_ascii_alphanumeric())
}

/// `true` when `s` is shaped like a plausible FRAGMENT of a separator-split
/// credential: alphanumeric-only and at least [`MIN_BRIDGE_FRAGMENT_LEN`]
/// bytes. Shared by the short-token anchor-admission check in
/// [`check_entropy_heuristic`] and by [`bridge_fragment_chain`]'s outward
/// walk. A long anchor can reach reconstruction without satisfying this
/// shape, but every neighboring fragment merged into its chain must satisfy
/// it. This stops the walk at a short trigger/glue word (`key`, `api`, `for`)
/// sitting immediately beside the real fragments (#1062).
fn is_bridge_fragment_shape(s: &str) -> bool {
    s.len() >= MIN_BRIDGE_FRAGMENT_LEN && s.bytes().all(|b| b.is_ascii_alphanumeric())
}

/// `true` when `s` holds no ASCII alphanumeric character at all — the same
/// predicate [`adjacent_gap_is_bridgeable`] applies to the byte-range GAP
/// between two tokenizer tokens, applied here to a tokenizer TOKEN itself
/// (`s` is always non-empty: the tokenizer filters empty tokens). A
/// delimiter-only token such as `---` sitting between two Unicode-separator
/// gaps (#1062) carries none of a credential's own
/// characters — it is exactly as transparent to reconstruction as the
/// surrounding whitespace/Unicode gaps are, so [`bridge_fragment_chain`]
/// treats it as glue to walk across, not as a chain-terminating non-fragment
/// token. A token can never be both this and [`is_bridge_fragment_shape`]:
/// the latter requires only alphanumeric bytes, this requires none.
fn is_delimiter_only_token(s: &str) -> bool {
    !s.bytes().any(|b| b.is_ascii_alphanumeric())
}

/// Looks outward from `tokens[edge]` in `dir` (`-1` = toward index 0, `+1` =
/// toward the end) for the next [`is_bridge_fragment_shape`] token, walking
/// transparently across up to [`MAX_BRIDGE_GLUE_TOKENS`] consecutive
/// [`is_delimiter_only_token`] glue tokens along the way. Every gap crossed
/// — including the ones on either side of a glue token — must be
/// [`adjacent_gap_is_bridgeable`]. Returns the found fragment's index, or
/// `None` if the walk runs off the end of `tokens`, meets a token that is
/// neither a fragment nor glue, meets a non-bridgeable gap, or exhausts the
/// glue budget before finding a fragment.
fn probe_bridge_fragment(
    tokens: &[(usize, &str)],
    text: &str,
    edge: usize,
    dir: isize,
) -> Option<usize> {
    let mut i = edge;
    let mut glue_skipped = 0usize;
    loop {
        let next_i = i.checked_add_signed(dir)?;
        if next_i >= tokens.len() {
            return None;
        }
        let (lo, hi) = if dir < 0 { (next_i, i) } else { (i, next_i) };
        let (lo_offset, lo_raw) = tokens[lo];
        let (hi_offset, _) = tokens[hi];
        let gap_start = lo_offset + lo_raw.len();
        if !adjacent_gap_is_bridgeable(text, gap_start, hi_offset) {
            return None;
        }
        let candidate = strip_delimiters(tokens[next_i].1);
        if is_bridge_fragment_shape(candidate) {
            return Some(next_i);
        }
        if is_delimiter_only_token(candidate) && glue_skipped < MAX_BRIDGE_GLUE_TOKENS {
            glue_skipped += 1;
            i = next_i;
            continue;
        }
        return None;
    }
}

/// Reconstructs the bounded chain of tokenizer fragments containing
/// `tokens[anchor_idx]`, by walking outward in both directions via
/// [`probe_bridge_fragment`] until the chain has reached
/// [`MAX_BRIDGE_FRAGMENTS`] real fragments or neither direction can extend
/// further. Returns each REAL fragment's [`strip_delimiters`]-ed body, in
/// document order, for the caller to recombine — any delimiter-only glue
/// tokens absorbed along the way (#1062) are dropped from the
/// result entirely, so a caller joining fragments with a space
/// ([`normalized_hex_credential_span`]) or concatenating them directly
/// (the generic entropy check) sees only the genuine fragments, exactly as
/// if the glue were more gap. Extends both directions every iteration so a
/// credential split with fragments on both sides of the anchor (e.g. the
/// anchor is the MIDDLE fragment of a three-way split) is fully
/// reconstructed, not just one side of it. A length-1 result means no
/// extension was possible — callers should skip further work in that case.
/// The anchor itself is included without a fragment-shape check; only outward
/// extensions are admitted through [`probe_bridge_fragment`].
fn bridge_fragment_chain<'a>(
    tokens: &[(usize, &'a str)],
    text: &str,
    anchor_idx: usize,
) -> Vec<&'a str> {
    let mut start = anchor_idx;
    let mut end = anchor_idx;
    let mut fragment_count = 1usize;

    loop {
        let mut extended = false;
        if fragment_count < MAX_BRIDGE_FRAGMENTS && start > 0 {
            if let Some(new_start) = probe_bridge_fragment(tokens, text, start, -1) {
                start = new_start;
                fragment_count += 1;
                extended = true;
            }
        }
        if fragment_count < MAX_BRIDGE_FRAGMENTS && end + 1 < tokens.len() {
            if let Some(new_end) = probe_bridge_fragment(tokens, text, end, 1) {
                end = new_end;
                fragment_count += 1;
                extended = true;
            }
        }
        if !extended {
            break;
        }
    }

    tokens[start..=end]
        .iter()
        .map(|&(_, raw)| strip_delimiters(raw))
        .filter(|stripped| !is_delimiter_only_token(stripped))
        .collect()
}

/// Extra backward truncation [`mask_bounded`] applies after it drops the
/// token straddling the window boundary.
///
/// `bridge_fragment_chain` can reconstruct a credential from up to
/// [`MAX_BRIDGE_FRAGMENTS`] whitespace-separated pieces, each individually
/// too short or low-entropy on its own to be recognized. The gap between two
/// fragments is deliberately unbounded in byte length
/// (`adjacent_gap_is_bridgeable`), so there is no finite forward lookahead
/// past the window boundary that could guarantee seeing every fragment of a
/// chain straddling the cut — a chain can be padded arbitrarily far past the
/// window by a single long glue token, which still counts as only one hop
/// against [`MAX_BRIDGE_GLUE_TOKENS`]. Rather than scan past the boundary,
/// this walks BACKWARD from it — data already read into the window, so the
/// extra work stays bounded by `window_chars` alone and needs no lookahead —
/// dropping every further bridge-fragment-shaped token chained to the
/// fragment [`mask_bounded`] already removed, spending the same
/// fragment-count and glue-token budgets [`bridge_fragment_chain`] would
/// spend walking outward from an anchor.
///
/// Runs unconditionally on every truncated window, regardless of whether the
/// window itself carries trigger-word context. `collect_mask_spans` step 6
/// admits trigger context from EITHER side of a fragment chain (a credential
/// like `<frag> <frag> <frag> is the api key for ...` is reconstructed by the
/// unbounded masker even though the trigger sits after the fragments), so a
/// trigger word that would justify keeping this window's tail may sit past
/// the window boundary — data this function, by construction, cannot see.
/// Gating the walk on an in-window trigger check would leave exactly that
/// case unprotected: the window carries no visible trigger, the walk would
/// never run, and any whole fragments already read into the window would
/// leak. The walk cannot distinguish a genuine chained fragment from an
/// unrelated fragment-shaped word sitting at the tail of an untriggered
/// window either; the trade this makes is dropping that word too rather than
/// risking a leaked credential fragment. The cost is bounded: at most
/// `MAX_BRIDGE_FRAGMENTS - 1` tokens of a tail that mask_bounded has already
/// decided to truncate.
///
/// Returns the byte offset to truncate `window` to, or `None` when nothing
/// beyond the already-trimmed token needs to go.
fn trailing_bridge_fragment_cut(window: &str) -> Option<usize> {
    let tokens = tokenize_entropy_tokens(window);
    let mut idx = tokens.len().checked_sub(1)?;
    let mut fragment_budget = MAX_BRIDGE_FRAGMENTS - 1;
    let mut glue_budget = MAX_BRIDGE_GLUE_TOKENS;
    let mut cut_at = None;

    loop {
        let (offset, raw) = tokens[idx];
        let candidate = strip_delimiters(raw);
        if is_bridge_fragment_shape(candidate) {
            if fragment_budget == 0 {
                break;
            }
            fragment_budget -= 1;
            glue_budget = MAX_BRIDGE_GLUE_TOKENS;
            cut_at = Some(offset);
        } else if is_delimiter_only_token(candidate) {
            if glue_budget == 0 {
                break;
            }
            glue_budget -= 1;
        } else {
            break;
        }

        if idx == 0 {
            break;
        }
        let (prev_offset, prev_raw) = tokens[idx - 1];
        let gap_start = prev_offset + prev_raw.len();
        if !adjacent_gap_is_bridgeable(window, gap_start, offset) {
            break;
        }
        idx -= 1;
    }

    cut_at
}

/// Returns `true` when `low_window` contains `needle` as a standalone word —
/// bounded on both sides by a character outside the word-char set (or
/// start/end of string) — rather than merely as a substring.
/// `underscore_is_word_char` selects the boundary rule the caller needs; see
/// `docs/api/secret_gate.md#contains_word` for the two deliberately different
/// rules and why each caller needs its own.
fn contains_word(low_window: &str, needle: &str, underscore_is_word_char: bool) -> bool {
    let is_word_char = |c: char| c.is_ascii_alphanumeric() || (underscore_is_word_char && c == '_');
    let mut start = 0;
    while let Some(rel) = low_window[start..].find(needle) {
        let abs = start + rel;
        let before_ok = abs == 0
            || low_window[..abs]
                .chars()
                .next_back()
                .is_none_or(|c| !is_word_char(c));
        let after_end = abs + needle.len();
        let after_ok = after_end >= low_window.len()
            || low_window[after_end..]
                .chars()
                .next()
                .is_none_or(|c| !is_word_char(c));
        if before_ok && after_ok {
            return true;
        }
        start = abs + needle.len().max(1);
    }
    false
}

/// Returns `true` when `low_window` contains the bare trigger word `needle`
/// as a standalone word, with underscore treated as a BOUNDARY (see
/// [`contains_word`]) — so `secret_key=…`/`auth_token=…`/`signing_key=…`
/// still match (on the `secret`/`auth`/`key` half), while pure letter-joined
/// collisions like `authorized`/`authentication`/`monkey`/`keyword` do not.
fn contains_bounded_word(low_window: &str, needle: &str) -> bool {
    if needle != "key" {
        return contains_word(low_window, needle, false);
    }
    low_window
        .split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
        .any(|label| {
            if !contains_word(label, needle, false) {
                return false;
            }
            let end = label.as_ptr() as usize - low_window.as_ptr() as usize + label.len();
            let after = low_window[end..].trim_start_matches(is_assignment_label_gap);
            !(is_lookup_key_label(label) && after.starts_with([':', '=']))
        })
}

fn is_assignment_label_gap(c: char) -> bool {
    matches!(c, '"' | '\'' | '`')
}

/// Closed vocabulary of member names whose `_key` suffix names a lookup
/// identifier rather than a credential (issue #2654). The exception is an
/// allowlist on purpose: any other `*_key` label keeps `key` as a credential
/// trigger, so unknown compounds such as `hmac_key`, `master_key`, `ssh_key`,
/// `jwt_key`, `webhook_key` or `license_key` stay refused. The match is the
/// whole label: a qualified spelling such as `left_association_key` or
/// `hmac_cache_key` is not in the vocabulary and keeps its trigger, because a
/// prefix rule would re-open every compound the list closes (`hmac_` is not a
/// trigger word, so `hmac_cache_key` would strip to a listed suffix).
const LOOKUP_KEY_LABELS: &[&str] = &[
    "association_key",
    "cache_key",
    "composite_key",
    "dedup_key",
    "foreign_key",
    "idempotency_key",
    "index_key",
    "lookup_key",
    "map_key",
    "natural_key",
    "partition_key",
    "primary_key",
    "range_key",
    "routing_key",
    "row_key",
    "search_key",
    "shard_key",
    "sort_key",
    "surrogate_key",
    "unique_key",
];

fn is_lookup_key_label(label: &str) -> bool {
    LOOKUP_KEY_LABELS.contains(&label)
}

/// Finds a canonical compound credential label beginning at an identifier
/// boundary. The trailing edge is deliberately unbounded so version suffixes
/// and larger underscore-composed labels remain protected.
fn compound_trigger(low_text: &str) -> Option<&'static str> {
    COMPOUND_TRIGGER_WORDS.iter().copied().find(|needle| {
        let mut start = 0;
        while let Some(rel) = low_text[start..].find(needle) {
            let abs = start + rel;
            let before_ok = abs == 0
                || low_text[..abs]
                    .chars()
                    .next_back()
                    .is_none_or(|c| !c.is_ascii_alphanumeric());
            if before_ok {
                return true;
            }
            start = abs + needle.len();
        }
        false
    })
}

fn find_trigger(text: &str, credential_label_only: bool) -> Option<&'static str> {
    let low = text.to_ascii_lowercase();
    TRIGGER_WORDS
        .iter()
        .copied()
        .find(|tw| contains_bounded_word(&low, tw))
        .or_else(|| compound_trigger(&low))
        .or_else(|| {
            ((!credential_label_only && has_standalone_token(&low)) || has_token_assignment(&low))
                .then_some("token")
        })
        .or_else(|| assignment_credential_trigger(&low))
}

/// Detect a credential-bearing assignment label before an `=` or `:`.
///
/// The separator may be preceded by whitespace or a JSON quote. Compound
/// triggers deliberately retain substring matching inside the label so common
/// version suffixes such as `api_keyv2` remain protected.
fn assignment_credential_trigger(low_text: &str) -> Option<&'static str> {
    low_text.char_indices().find_map(|(index, ch)| {
        if !matches!(ch, '=' | ':') {
            return None;
        }
        let before =
            low_text[..index].trim_end_matches(|c: char| !c.is_ascii_alphanumeric() && c != '_');
        let label = before
            .rsplit(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .next()
            .unwrap_or_default();
        COMPOUND_TRIGGER_WORDS
            .iter()
            .copied()
            .find(|needle| label.contains(needle))
            .or_else(|| {
                TRIGGER_WORDS.iter().copied().find(|tw| {
                    (*tw != "key"
                        || !is_lookup_key_label(label)
                        || !low_text[before.len()..index]
                            .chars()
                            .all(is_assignment_label_gap))
                        && contains_bounded_word(label, tw)
                })
            })
            .or_else(|| (label == "token").then_some("token"))
    })
}

/// Detect credential labels embedded in the same whitespace token as a value.
///
/// The surrounding-context scan deliberately excludes the candidate token so
/// a trigger word inside a path cannot make that path self-trigger. Credential
/// assignments still need to fire when no whitespace separates label and
/// value, including JSON-like forms. Underscore-delimited config identifiers
/// without an assignment are retained for compatibility with shapes such as
/// `session_secret_<value>`.
fn inline_credential_trigger(raw_token: &str) -> Option<&'static str> {
    let low = raw_token.to_ascii_lowercase();
    assignment_credential_trigger(&low).or_else(|| {
        if !low.contains(['/', '-', '.']) && low.contains('_') {
            COMPOUND_TRIGGER_WORDS
                .iter()
                .copied()
                .find(|needle| low.contains(needle))
                .or_else(|| {
                    TRIGGER_WORDS
                        .iter()
                        .copied()
                        .find(|tw| contains_bounded_word(&low, tw))
                })
        } else {
            None
        }
    })
}

/// Returns `true` when `low_window` contains the word `token` as a standalone
/// word, with underscore treated as a WORD CHARACTER / continuation (see
/// [`contains_word`]) — but NOT as part of compound identifiers such as
/// `tokenizer`, `token_count`, or `next_token`. This underscore-as-
/// continuation rule is deliberately different from
/// [`contains_bounded_word`]: `token` alone is not a
/// credential trigger (it fires on too many benign technical terms), so it
/// needs the narrower, underscore-inclusive standalone-word definition,
/// whereas the bare `TRIGGER_WORDS` need underscore-joined compounds like
/// `secret_key` to still register.
fn has_standalone_token(low_window: &str) -> bool {
    contains_word(low_window, "token", true)
}

/// Returns `true` when `low_window` contains the assignment form `token=` or
/// `token:` where the `token` identifier has a word boundary BEFORE it.
///
/// This is boundary-aware so that compound identifiers like `next_token:` or
/// `pagination_token=` do NOT trigger — only a standalone `token=`/`token:`
/// at the start of a field name does.
///
/// Examples that return `true`:  `token=<value>`, `token: <value>`,
///   `"token": "<value>"` (JSON key-value pairs).
/// Examples that return `false`: `next_token: <value>`,
///   `pagination_token=<value>`, `token_count: <value>`.
fn has_token_assignment(low_window: &str) -> bool {
    let needle = "token";
    let mut start = 0;
    while let Some(rel) = low_window[start..].find(needle) {
        let abs = start + rel;
        // Require a word boundary BEFORE `token`.
        let before_ok = abs == 0
            || low_window[..abs]
                .chars()
                .next_back()
                .is_none_or(|c| !c.is_ascii_alphanumeric() && c != '_');
        let after_end = abs + needle.len();
        // Require `=` or `:` immediately after `token` (possibly with surrounding
        // whitespace or quotes stripped by the time we see the lowercased window).
        let after_char = low_window[after_end..].chars().next();
        let after_is_assign = matches!(after_char, Some('=') | Some(':'));
        if before_ok && after_is_assign {
            return true;
        }
        start = abs + needle.len().max(1);
    }
    false
}

// ─── Allowlist helpers ───────────────────────────────────────────────────────

/// Returns `true` for pure-hex tokens (case-insensitive, optional `0x`/`0X` prefix,
/// 8–128 chars) — git SHAs, checksum digests, uuid-hex without hyphens.
///
/// This helper is used with context: pure-hex tokens near credential trigger words
/// are NOT allowlisted (see `check_entropy_heuristic`).  Only call this function
/// when you have already confirmed no trigger context is nearby.
fn is_pure_hex(token: &str) -> bool {
    let hex_part = token
        .strip_prefix("0x")
        .or(token.strip_prefix("0X"))
        .unwrap_or(token);
    hex_part.len() >= 8 && hex_part.len() <= 128 && hex_part.bytes().all(|b| b.is_ascii_hexdigit())
}

/// Returns `true` for tokens that are unambiguous base64/base64url content
/// hashes with an explicit `sha<N>-` prefix (SRI hash, npm lockfile integrity).
/// Bare base64 of the same length WITHOUT the prefix is NOT allowlisted — see
/// `docs/api/secret_gate.md#is_base64_content_hash` for the full criteria list and
/// why the explicit prefix is required.
fn is_base64_content_hash(token: &str) -> bool {
    // Known vendor prefixes — never allowlist even if they look like base64.
    // Includes bare `sk-` to prevent OpenAI-shaped tokens from being allowlisted.
    const VENDOR_PREFIXES: &[&str] = &[
        "sk-",
        "rk_live_",
        "fm2_",
        "vercel_",
        "xoxb-",
        "xoxa-",
        "xoxp-",
        "xoxr-",
        "xoxs-",
        "ghp_",
        "gho_",
        "ghu_",
        "ghs_",
        "ghr_",
        "github_pat_",
        "AKIA",
        "ASIA",
        "AGE-SECRET-KEY-",
        "FlyV1",
    ];
    if VENDOR_PREFIXES.iter().any(|p| token.starts_with(p)) {
        return false;
    }
    // Require an explicit SRI `sha[0-9]+-` prefix.  Bare base64 at sha-length
    // is NOT allowlisted — it is indistinguishable from a real API token.
    let body = if let Some(rest) = token.strip_prefix("sha") {
        // rest starts with digits followed by '-'
        let dash = rest.find('-').unwrap_or(rest.len());
        let digits = &rest[..dash];
        if !digits.is_empty() && digits.bytes().all(|b| b.is_ascii_digit()) && dash < rest.len() {
            &rest[dash + 1..] // everything after "sha<digits>-"
        } else {
            return false; // no valid sha<N>- prefix → not a known content hash
        }
    } else {
        return false; // no sha prefix → not allowlisted
    };
    // Strip optional padding (at most 2 `=`).
    let stripped = body.trim_end_matches('=');
    let pad_removed = body.len() - stripped.len();
    if pad_removed > 2 {
        return false;
    }
    // Accept only SHA-family content-hash lengths (43, 64, 86–88 chars unpadded).
    let n = stripped.len();
    if n != 43 && n != 64 && !(86..=88).contains(&n) {
        return false;
    }
    // Accept both standard-base64 and URL-safe-base64 alphabets.
    stripped
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b == b'+' || b == b'/' || b == b'-' || b == b'_')
}

/// Structural separators that gate entry into [`is_structured_identifier`]
/// (rule 1: the token must contain at least one of these). The actual run
/// decomposition (rule 2) splits on every non-alphanumeric character, not
/// just these four — see the doc comment on `is_structured_identifier`.
const STRUCTURAL_SEPARATORS: [char; 4] = ['/', '-', '_', '.'];

/// Largest length a single path/branch/identifier segment (a "run" between
/// separators) may have and still be considered word-shaped.
const MAX_RUN_LEN: usize = 24;

/// Runs whose letter portion is at or below this length skip the
/// case-transition-density check: density is not a meaningful signal on very
/// short runs (e.g. `R1`, `v2`, `ADR`).
const DENSITY_EXEMPT_LETTER_LEN: usize = 4;

/// Maximum case-transition density (transitions divided by letter_count - 1)
/// a run's letter portion may have and still be considered word-shaped.
const MAX_CASE_TRANSITION_DENSITY: f64 = 0.3;

/// Returns `true` when `token` is shaped like a file path, branch name, or
/// other structured identifier rather than a high-entropy secret (word-shaped
/// runs separated by `/`, `-`, `_`, `.`). Exempts from the entropy heuristic
/// ONLY outside trigger context — see the module doc and
/// `docs/api/secret_gate.md#is_structured_identifier` for the run-shape criteria.
fn is_structured_identifier(token: &str) -> bool {
    if !token.contains(|c: char| STRUCTURAL_SEPARATORS.contains(&c)) {
        return false;
    }
    let runs: Vec<&str> = token
        .split(|c: char| !c.is_ascii_alphanumeric())
        .filter(|r| !r.is_empty())
        .collect();
    runs.len() >= 2 && runs.iter().all(|run| is_word_shaped_run(run))
}

/// A single run (segment between structural separators) is word-shaped when
/// it matches `[A-Za-z]+[0-9]*` or `[0-9]+`, is at most [`MAX_RUN_LEN`] chars,
/// and (for the letters-then-digits form) its letter portion has a low
/// case-transition density.
fn is_word_shaped_run(run: &str) -> bool {
    if run.is_empty() || run.len() > MAX_RUN_LEN {
        return false;
    }
    let bytes = run.as_bytes();
    if bytes.iter().all(|b| b.is_ascii_digit()) {
        return true;
    }
    let letter_end = bytes
        .iter()
        .position(|b| !b.is_ascii_alphabetic())
        .unwrap_or(bytes.len());
    // A run that does not start with a letter, and is not pure digits (ruled
    // out above), mixes digits and letters in a shape other than
    // letters-then-digits — not word-shaped.
    if letter_end == 0 {
        return false;
    }
    // Everything after the leading letters must be digits only (no further
    // letters), else the run is not the `[A-Za-z]+[0-9]*` shape.
    if !bytes[letter_end..].iter().all(|b| b.is_ascii_digit()) {
        return false;
    }
    case_transition_density_ok(&run[..letter_end])
}

/// `true` when the case-transition density of `letters` (an all-ASCII-letter
/// string) is at or below [`MAX_CASE_TRANSITION_DENSITY`]. A transition is an
/// adjacent letter pair where one side is uppercase and the other is not.
/// Runs with few enough letters pass automatically (see
/// [`DENSITY_EXEMPT_LETTER_LEN`]) since density is noisy on short strings.
fn case_transition_density_ok(letters: &str) -> bool {
    let chars: Vec<char> = letters.chars().collect();
    if chars.len() <= DENSITY_EXEMPT_LETTER_LEN {
        return true;
    }
    let transitions = chars
        .windows(2)
        .filter(|w| w[0].is_ascii_uppercase() != w[1].is_ascii_uppercase())
        .count();
    let density = transitions as f64 / (chars.len() - 1) as f64;
    density <= MAX_CASE_TRANSITION_DENSITY
}

/// `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
fn is_uuid_canonical(s: &str) -> bool {
    let b = s.as_bytes();
    if b.len() != 36 {
        return false;
    }
    b[8] == b'-'
        && b[13] == b'-'
        && b[18] == b'-'
        && b[23] == b'-'
        && b[..8].iter().all(|c| c.is_ascii_hexdigit())
        && b[9..13].iter().all(|c| c.is_ascii_hexdigit())
        && b[14..18].iter().all(|c| c.is_ascii_hexdigit())
        && b[19..23].iter().all(|c| c.is_ascii_hexdigit())
        && b[24..].iter().all(|c| c.is_ascii_hexdigit())
}

/// Strip common wrapping characters (`"`, `'`, `` ` ``, `:`, `=`) from both ends.
fn strip_delimiters(s: &str) -> &str {
    s.trim_matches(|c| matches!(c, '"' | '\'' | '`' | ':' | '=' | ',' | ';'))
}

/// Strip `{}()[]"'.,;` from both ends of `s`, repeatedly (JSON nests one
/// wrapper inside another).
fn strip_wrappers(s: &str) -> &str {
    s.trim_matches(|c: char| {
        matches!(
            c,
            '{' | '}' | '(' | ')' | '[' | ']' | '"' | '\'' | '`' | '.' | ',' | ';'
        )
    })
}

fn wrapper_strip_repeated(token: &str) -> &str {
    let mut cur = token;
    loop {
        let next = strip_wrappers(cur);
        if next == cur {
            return cur;
        }
        cur = next;
    }
}

/// Yields every candidate value an assignment/wrapper-glued token could
/// contain, for the near-trigger UUID/content-hash exact-shape checks only.
/// See `docs/api/secret_gate.md#value_candidates` for why every `=`/`:` suffix
/// must be tried rather than just the first or last.
fn value_candidates(token: &str) -> impl Iterator<Item = &str> {
    let cur = wrapper_strip_repeated(token);
    std::iter::once(cur).chain(cur.char_indices().filter_map(move |(i, c)| {
        if c == '=' || c == ':' {
            let after = strip_wrappers(&cur[i + c.len_utf8()..]);
            if !after.is_empty() {
                return Some(after);
            }
        }
        None
    }))
}

// ─── Utilities ───────────────────────────────────────────────────────────────

/// Extract a contiguous token (non-whitespace chars) starting at the beginning of `s`.
fn extract_token(s: &str) -> &str {
    let end = s
        .find(|c: char| c.is_whitespace() || c == '\n' || c == '\r')
        .unwrap_or(s.len());
    &s[..end]
}

/// Shannon entropy in bits per character.
///
/// H = -∑ p_i log2(p_i)
fn shannon_entropy(bytes: &[u8]) -> f64 {
    if bytes.is_empty() {
        return 0.0;
    }
    let mut counts = [0u32; 256];
    for &b in bytes {
        counts[b as usize] += 1;
    }
    let len = bytes.len() as f64;
    counts
        .iter()
        .filter(|&&c| c > 0)
        .map(|&c| {
            let p = c as f64 / len;
            -p * p.log2()
        })
        .sum()
}

/// Build a `SecretMatch` from a detector name and the candidate string.
///
/// The masked excerpt is: first 6 chars + "..." + total length.
/// Never includes more than 6 chars of the actual value.
fn build_match(detector: &'static str, candidate: &str) -> SecretMatch {
    let chars: Vec<char> = candidate.chars().collect();
    let preview: String = chars.iter().take(6).collect();
    let masked = format!("{}...{}chars", preview, chars.len());
    SecretMatch {
        detector,
        trigger: None,
        masked,
        location: None,
    }
}

#[cfg(test)]
#[path = "secret_gate/issue_2655_tests.rs"]
mod issue_2655_tests;

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
#[path = "secret_gate_tests.rs"]
mod tests;

// ─── Corpus replay harness (manual, opt-in) ─────────────────────────────────
//
// Measures how many real note/entity strings the gate blocks, so a detector
// change can be evaluated against production content rather than intuition
// (see the module doc). Opens the target database
// STRICTLY read-only (`SQLITE_OPEN_READ_ONLY`) and never mutates it. Point
// `KHIVE_REPLAY_DB` at a copy or a live KG database file path; the harness
// never writes, locks aggressively, or deletes anything.
//
// Run with: `KHIVE_REPLAY_DB=/path/to/khive.db cargo test -p khive-runtime \
//   --release -- --ignored --nocapture corpus_replay`
#[cfg(test)]
#[path = "secret_gate/corpus_replay_tests.rs"]
mod corpus_replay;
